---
title: "Chapter XYZ: Weight of Evidence"
execute:
  enabled: true
format:
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
---


# Introduction

The aim of legal-fact finding is, quite literally, to find out the facts. To find out the facts---for example, whether or not the defendant embezzled a large sum of money as the prosecution claims---it is necessary to gather, scrutinize and assess evidence from a variety of sources. One side will present evidence against the defendant, and the other side will present evidence in favor of the defendant. But this adversarial process must come to an end at some point. A decision about the facts must be made based on the evidence presented up to that point. Did the defendant commit the wrongdoing they are accused of?  This decision is preceded by another, namely a decision about whether the process of presenting, scrutinizing and assessing evidence should come to an end. 

In principle, more evidence could always be presented about a disputed factual issue: witnesses, forensic experts, telephone conversations, camera recordings, and so on.   But, at some point, gathering more evidence will no longer bring value in addition to what the evidence already available could do because the costs of seeking more evidence may become too great. 

## Epistemic value or informativeness 

What does it mean for new evidence to be valuable? Some terminology can help here. New evidence can be *epistemically* or *informationally* valuable. It provides novel information that existing, already available evidence did not provide, where this novel information can be consistent or inconsistent with the existing evidence.  New evidence can be informationally valuable even when it simply agrees with other evidence, for example, when two witnesses report having seen the same thing.  So, new evidence is epistemically valuable if it adds new information or simply strengthens the credibility of existing evidence. But, at some point, seeking more evidence will become less and less epistemically valuable. 


## Decisional value

The epistemic value of new evidence need not be the same as its *decisional* value. A new piece of evidence is decisionally valuable if, when added to the existing body of evidence, it would change the trial decision, given whatever decision criterion is used. A new piece of evidence can be epistemically valuable without being decisionally valuable, but not the other way around. Perhaps a new piece of evidence can add novel information or strengthen the credibility of other evidence, but these changes might not be significant enough to change the decision.


## When to stop seeking more evidence?

If new evidence is regarded as valuable in the sense specified, should the trial decision be postponed to seek it? Not necessarily. We should not assume that evidence that is informationally and decisionally valuable should be *ipso facto* sought by investigators or that trial proceedings should be prolonged in search of this evidence. The evidence could be too expensive or even impossible to obtain. Having a detailed camera recording of what happened could have great informational and decisional value, but this does not mean a trial judgment must be postponed until the recording is obtained. The costs of obtaining it might be too great. 

In general, the question of whether to stop seeking more evidence is a practical question, moral or political. It requires balancing the costs of seeking more evidence with the informational and decisional value of the new evidence. These costs can be monetary, but in time and delayed trial decisions. Before performing this balancing act, however, we need an account of when additional evidence is epistemically and decisionally valuable. Here we aim to provide an account of the informational value of new evidence. This account then can be used to formulate an account of the decisional value of the evidence based on one's decision criterion of choice.


## Prospective and retrospective questions, and remedies

We identified three different 
types of questions: 

- What is the epistemic or informational value of an item of evidence?

- What is its decisional value?

- Should the trial decision be postponed to seek more evidence that is valuable?

These three questions are typically viewed prospectively but they can also be formulated retrospectively.  The first two questions about the epistemic and decisional value of evidence need not be confined to evidence that has not yet been obtained. They could also concern evidence that was obtained. Or they could be about evidence that is missing and could no longer be obtained. In this sense, they can be both prospective and retrospective. 

The prospective questions inform what investigators, prosecutors or defense lawyers should do as they seek more evidence. But even if the decision about seeking more evidence is foreclosed, one can still ask retrospectively what the investigators should have done. The latter question, in turn, can guide the formulation of possible remedies, say whether the defendant should be acquitted because of missing evidence that the investigator should have gathered.  When a piece of evidence is missing---say, because it was destroyed by accident or is no longer available---one of the two parties 
may benefit from this absence. Then, the question arises of how this 
absence should affect decisions about the facts.



## Stylized legal case

A stylized legal case will help fix ideas. A more detailed discussion of realistic legal cases is to be found at the end of this chapter. 

The defendant confessed to having killed the victim when he burglarized the victim's apartment and stole cash and other valuables kept in a tin box. The confession was the prosecution's key incriminating evidence, but at trial, the defense raised doubts that the defendant was covering up for his son. These doubts were corroborated by the fact that the defendant was rather short and it would take a tall person to kill the victim. And the defendant's son was much taller. On the other hand, the defendant confessed and provided abundant details all consistent with the findings of the investigators. One piece of evidence is missing: because the defendant confessed right away, the investigators did not examine the tin box for fingerprints. The box was later wiped clean. Had they found the son's fingerprints on it, that would be evidence of the defendant's innocence. 

This case raises several questions:

- First, questions on the epistemic or informational value of the evidence. Retrospectively---knowing what we know now---what is the value of the missing fingerprint evidence? Prospectively---knowing what the investigators knew back them---what was the value of the fingerprint evidence? 

- Second, questions about the decision. Retrospectively, would the fingerprint evidence---if it had been obtained during the investigation---have changed the trial decision? 

- Third, questions about what to do. Prospectively or retrospectively, what should the investigators have done? This question is relevant to another, related yet different question: Should the defendant be acquitted because of the missing fingerprint evidence? Should the jurors be instructed to make an adverse inference against one of the parties, say the prosecutor?



## Weight v. balance of evidence 

Another bit of terminology is the distinction between 'weight of evidence' and 'balance of evidence'. This distinction goes back to Keynes. The balance tracks whether the evidence presented tips for or against a hypothesis of interest. Weight, for Keynes, tracks the quantity of the evidence. Here both balance and weight are properties of the *total* body of evidence. 

Instead, the notion of epistemic or informational value of evidence we are after is a property of a piece of evidence relative to an existing body of other evidence. 








[@sec-prob-diff]

# First pass  {#sec-prob-diff}

## Absolute probability difference 

Let's start with the simplest account of the value of new evidence, mostly in terms of a probability change. Formally, the epistemic value of new evidence $E_n$, against the background of other evidence $E_b$, can be measured by the probability change the new evidence brings about relative to a hypothesis $H$ of interest. So the epistemic value of $E_n$ given background evidence $E_b$ relative to hypothesis $H$ is the absolute difference 
$$|P(H \vert E_b)-P(H \vert E_b \wedge E_n)|.$$ 
The greater this difference, positive or negative, the greater the epistemic or infomational value of the new evidence. The smaller the difference, the lesser the value of the new evidence.

Dahlman's account of informativeness closely follows this definition. Nance offers a similar account. For him, the informational value (or weight) of the evidence is the absolute value of the log likelihood ratio 
$$log(\frac{P(E_n \vert H \wedge E_b)}{P(E_n \vert \neg H \wedge E_b)}).$$ 
As we know, likelihood ratios mirror changes in probabilities: the greater the likelihood ratio, the greater the change upwards, and the lower the likelihood ratio, the greater the change downwards.

## Objection

This account, however, is not completely satisfactory, as it may count additional evidence as worthless, while it is instead quite valuable. Suppose two witnesses testify one in favor and another against the defendant, one says they were with the defendant when the crime occurred away from the crime scene, while the other says they saw the defendant around the crime scene at the relevant time. Absent any reason to believe one witness more than the other, assume the chances are 50/50, that is $P(G \vert W1 \wedge W2)=.5$ Next, we consult two other witnesses, and again we find one favoring the defendant and the other incriminating the defendant. So, again,  $P(G \vert W1 \wedge W2 \wedge W2 \wedge W5)=.5$. The probabilities have not changed, but the testimonies of the two additional witnesses are not worthless.

## Weighted probability difference

Here is a quick fix. True, after listening to the two additional witnesses, we realize their input is worthless. But *before* listening to them, we did not know what they would have said. They could have spoken both against (or in favor) of the defendant, and in that case, the probability of $G$ would have changed quite dramatically, either upwards or downwards. So, there are three possible scenarios: ($S_1$) they both speak against the defendant; ($S_2$) they both speak in favor; and ($S_3$) they speak one in favor and the other against. If each scenario is 1/3 likely, there is a 2/3 chance the new evidence would be epistemically valuable and only a 1/3 chance it would not be. So, overall, the new evidence is valuable.

The proposal would be this. The epistemic value of new evidence $E_n$ given $E_b$ and relative to $H$ is the weighted sum of the difference $P(H \vert E_b)-P(H \vert E_b \wedge E^i_n)$, where the weights are the probabilities of the scenarios $P(S_i)$ that could materialize and $i\in\{1, 2, 3, .... k\}$:

\begin{equation*}
\sum_1^k P(S_i) \times |P(H \vert E_b)-P(H \vert E_b \wedge E^i_n)| 
\end{equation*}

## Another objection (or recall higher-order probabilities)
 
 
This quick fix is still not satisfactory. In the previous chapter, we argued that precise probabilities are not enough because they fail to capture higher-order uncertainty. If precise probabilities are not enough to model uncertainty, then an account of the epistemic or informational value of new evidence that is based on precise probabilities will fall short for similar reasons.  

 Suppose an expert who listened to a telephone conversation testifies that the voice of the caller matches the defendant's voice. To quantify the uncertainty associated with the voice match, the expert introduces as is customary the random match probability, a number that expresses the likelihood that a random person would still be a match, simply by coincidence. This number is based on a probability model and sample data, so it is itself subject to uncertainty.^[This uncertainty is higher-order and is best modeled by a higher probability, a probability of a probability. What is the probability that the random match probability is what the expert says it is? Since the random match probability can take any value between 0 and 1, each of these values will have a higher-order probability, or in other words, there will be a distribution over the first-order probabilities (in this case, a distribution over the possible random match probabilities).] 

 Compare the voice expert with a genetic expert who testifies that the defendant genetically matches the crime traces. Suppose the genetic expert and the voice expert both testify, in different trials, that the defendant is a match, and they both give roughly similar random match probability. Should we say that both forms of evidence have the same value? After all, they change the guilt probability to the same extent. But the genetic match is better evidence than the voice match: better sample, better models, etc. Sticking to first-order probabilities neglects this additional layer of uncertainty and the difference between genetic match and voice match. The next section outlines the right account of the epistemic or informational value of the evidence. This account incorporates higher-order uncertainty. 


# Our proposal 

 The standard approach models the informational value of new evidence $E_n$ as the difference between posterior and prior (first-order) probabilities, that is, the difference between $P(H \vert E_n)$ and $P(H)$. Our approach models informational value as the difference between the informativeness of posterior and prior (second-order) distributions of (first-order) probabilities. 

Say you have gathered some fallible evidence up to that point about hypothesis $H$. Instead of representing your uncertainty about $H$ up to that point by the precise, prior probability $P(H)$, higher-order probabilities offer a more adequate model of uncertainty. They can capture the possible uncertainty associated with first-order probabilities (see discussion in Chapter ZZZ). Let $PRIOR$ be a probability distribution defined over the possible values of the first-order, prior probability $P(H)$. This is your prior state of uncertainty about $H$ given the evidence you have up to that point. Now you want to know the informational value of the new evidence $E_n$. As you take this evidence into account, your state of uncertainty will change accordingly. Let $POST_{E_n}$ be the probability distribution defined over the possible values of the first-order, posterior probability $P(H \vert E_n)$. 

## Difference between prior and posterior higher-order distributions 

Intuitively, the change that new evidence brings about to your state of uncertainty---that is, the change from prior to posterior distributions---is the informational value of the evidence.  Note that the higher-order prior and posterior distributions can have different shapes: they can have a peak and be more or less concentrated around it, or they can have multiple peaks and be more or less concentrated around them. The more spread out a distribution, the less informative it will be. So the change in shape from prior to posterior distributions brought about by new evidence will correspond to its informational value. To make this point more precise, we need a couple of notions: first, a measure of the informativeness of prior and posterior distributions; and second, a measure of the change in informativeness across distributions.

 In general, the informativeness of a distribution $X$ is defined using standard information theory as $1 - H(X)$, where $H$ is the entropy of the distribution. Entropy measures lack of information. Entropy is typically defined as follows: 

\begin{align*}
H(X)  & = \sum_x \mathsf{P}(X=x) \log_2 \frac{1}{\mathsf{P}(X=x)} =
- \sum \mathsf{P}(x) \log_2 \mathsf{P}(x),
\end{align*}

\noindent 
where $x$ stands for a possible value 
of the distribution $X$, for example, a first-order probability that the distributions $PRIOR$ or $POST$ could take.   Crucially, entropy is not a measure of the amount of information contained in a distribution. 
It is rather the opposite: the expected amount of information you receive 
once you learn the value of $X$. The less informative a distribution, the more you expect
to learn when you find out the value of $X$, the higher the entropy. 
The least informative distribution, the one with the highest entropy, is the uniform distribution. 

The informational value of new evidence $E_n$ is modeled by the difference between the informativeness of prior and posterior distributions. This difference boils down to the difference between the entropies of the distribution $H(PRIOR)-H(POST_{E_n})$. If this difference is positive, the entropy has decreased (and thus informativeness has increased). Conversely, if the difference is negative, the entropy has increased (and thus informativeness has decreased). This difference can be normalized by dividing by the entropy of the uniform distribution which is by definition maximal. So our account of the value of new evidence $E_n$ is as follows:

$$\frac{H(PRIOR)-H(POST_{E_n})}{H(UNIFORM)}$$

## Expected difference


# Legal cases


## Tin box



Let's now revisit in more detail the tin box case we mentioned earlier. The defendant confessed right after the police found the victim dead and began the investigation. While confessions can be weak incriminating evidence when they are coerced, uncoerced confessions seem highly probative. The many details contained in the defendant's confession convinced the investigators they had a very strong case. No other investigation seemed necessary. This decision turned out to be premature, as know now. 

At trial, the defense put forward an alternative hypothesis: the defendant was covering up for his son. 
The missing evidence, the perpetrator's fingerprints on the tin box in which the money and valuables were kept now becomes an essential piece of evidence. Too bad the tin box was wiped 
clean and the fingerprints on it are lost forever. It is clear, even without any formal modeling, that the fingerprints on the tin box would be of great value. If they match the son's fingerprints, they would be strong evidence against the son. If they match the defendant's fingerprint, they would be equally strong evidence against the defendant. It is as though the fingerprints alone could decide the case. Too bad they are given forever.

But without the fingerprints, what is the state of uncertainty given the available evidence?  Without the additional hypothesis that the defendant was covering up for his son, the likelihood ratio associated with the confession and relative to the competing hypotheses would seem very high:

$$\frac{P(\text{defendant confessed} \vert \text{defendand did it})}{P(\text{defendant confessed} \vert \text{some else did it})}>>>>>1$$

Once the two suspects are narrowed down to the defendant and his son, the likelihood ratio goes down to about one. The confession becomes  worthless evidence:
$$\frac{P(\text{defendant confessed} \vert \text{defendand did it})}{P(\text{defendant confessed} \vert \text{defendant's son did it})}=1$$

Or does it? One might argue that, oddly, the defendant waited until the trial to bring up the son as a possible perpetrator. Couldn't that just be a trick? To confess first and then to raise a reasonable doubt that cannot be settled. But ultimately it seems that the police was to blame. Why did they not conduct a more careful examination of the trace evidence available at the crime scene? Why blindly trust the defendant's confession?

As these brief remarks suggest, an informal examination of the case will not get us too far. What is the state of uncertainty given the available evidence? What information could the fingerprint add to the case? There are three key items of information in the case: (a) the confession;  (b) the angle at which the victim was stabbed; and (c) the missing fingerprints. How should this information be combined? 

We can make the following assumptions: (a) the confession is more likely under the hypothesis that the hypothesis that the defendant did it than the son did not, but there is significant higher-order uncertainty about this assessment of relative probabilities. (b) The angle of stabbing is more likely under the hypothesis that the son did not than the defendant did it, and there is less higher-order uncertainty about this relative probability assessment. 
























## Missing fingers




