---
title: "Corroboration"
author: "Marcello/Rafal"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - style.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [../references/referencesMRbook.bib]
csl: [../references/apa-6th-edition.csl]
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# On Gardiner's paper on corroboration

The  claim is that 'probabilistic balance' cannot account 
for corroboration because:

1. corroborating evidence increases the probability of a hypothesis

2. but also rules out relevant error possibilities 

Suppose W1 claims p and also W2 claims p. They corroborate one another. So the probability of p based on W1 alone is lower than the probability of p based on W1 and W2. But there is something else. W1 could be wrong in various wasy: was lying, got confused, forgot, etc. The convergence of W1 and W2 helps to eliminate these error possibilities. 

Why cannot 'probabilistic balance'  account for that? There could be corroborating evidence that has marginal 
effect on probabilistic balance---the probability of the hypothesis moves from very high to slightly higher. Yet, despite the slight change in probability, corroboration has a strong credibility boosting effect that probability cannot capture. This can be explained by noting that corroborating evidence eliminate salient error possibilities, even though it does not change dramatically the probability of the hypothesis of interest.

This is the motivating example Gardiner uses:

> A cold-hit DNA search—that is, trawling through DNA databases for similar allele patterns-identifies a match with Brett. The allele profile is rare and so the chance of somebody unrelated to Brett having a similar profile is extremely low.1 But the database does not include the entire population. This DNA match makes Brett the lead suspect and, indeed, renders it probable Brett is guilty. Later Corey, a known fence, is apprehended selling the watch. When questioned, Corey says ‘I bought the watch from someone called Brett. He stole it.’

I wonder whether this example is correct:

- Is the guilt probability based on DNA match  that high? If we take error probabilities into account, such as false positives, the probability isn't that high, as shown in the likelihood ratio chapter. 

- Not sure if corroboration based Corey's assertion is negligible. If we measure the strength of evidence in terms of LR or BF, there is going to be a stronger difference, right?

Other questions:

- How does Rafal's probabilistic account of corroboration cope with this kind of example?

- Does relying on a specific story, rather than the generic claim 'the defendant is guilt', address Gardiner's challenge? 


Comments I sent to Gardiner about her paper (on April 1, 2022):

1) First, a comment about the DNA case you start out with. A lot hinges on how the case is defined. If all the facts are settled in sufficient detail and the only question open is who did it, a DNA match can be powerful in addressing this identity question. Many courts said, perhaps mistakenly, that it is sufficient for a conviction under such circumstances. See the cases cited by Andrea Roth.  But, even under such circumstances, I am not sure it is uncontroversial to say that the probability of guilt is 99.5% and it increases only marginally by corroborating evidence. It might actually be lower and increase by quite a bit because the corroborating evidence bears on the claim the defendant did it ('he stole it'), while the match bears on the fact that the defendant is the source of the crime traces. So there are many details up for discussion in that example. 

2) I kept asking myself, couldn't the relevance of error possibilities be a matter of how probable they are and whether they meet a probabilistic threshold of relevance? Maybe this thought is wrong, but I wanted you to say why it is wrong.  In a DNA evidence case, the probability that aliens did it (a distant, irrelevant error possibility) seems lower than the probability that a twin with the same genetic profile did it (a less distant, possibly relevant, error probability). 

    2b) A related comment. You say there are error possibilities which are equally probable, yet one is relevant and the other is not. Do you have in mind lottery/newspaper scenarios? But what about legal cases? On pp.11-12, you suggest that two items of evidence may affect the posterior probability of guilt to the same extent, even though one addresses a relevant error possibility while the other does not. The example consists of the evidence "Holly was in the US when the crime occurred" and "police never framed or conspired against Holly in the past". It is not clear to me which of these two items of evidence you think  addresses a relevant error possibility. Maybe the fact that the police conspire against people isn't relevant because we tend to think that police do not do such things. But again, isn't this because we think this is less likely than say the possibility that Holly would have been in another country?

3) To set up the question of corroboration, you need an account  of what it means for two items of evidence to be independent. Two witnesses who are looking at the same scene aren't independent because, if they are truthful and accurate, they must report the same thing.  The notion of independence at work here is one of conditional probabilistic independence given the target hypothesis. I do not know how a relevant alternative theory can provide an account of independence, or perhaps needs to borrow the probabilistic one. 

4) Towards the end, pp. 13 onwards, you examine whether a single piece of evidence may suffice for a conviction or whether a corroboration requirement applies. Some have proposed a ban against single-evidence convictions, but virtually any legal system allows a conviction based on a single piece of evidence.  (Interestingly, Roman and medieval law did not allow that, but that was before the rationalistic principles of "free proof" took hold.) Saying that a single item suffices for a conviction is misleading, though, because a trial is adversarial and so, even if there is a single item of evidence, there is always other ancillary information, say, what the witness said in response to questions.  

    4b) Relatedly, it seems to me, what counts as a relevant error possibility is not defined before the trial. It depends on what the two sides disagree about. That an animal killed the victim might not be relevant at first, but might become relevant as more information comes in. So, I am not sure I'd reject your claim 2 on p. 13, but I'd say it needs to be stated more clearly, in a way that takes into account how adversarial scrutiny affects the formation of error possibilities. 
















