---
title: ""
author: ""
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - Rafal_latex6.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [LP-SEP-FINAL6.bib, munich4.bib]
csl: transactions-on-computational-logic.csl
---






```{r setup, include=FALSE}
library(ggplot2)
library(ggthemes)
knitr::opts_chunk$set(echo = TRUE)
```




\begin{center}
\large {\sc \textbf{Rethinking Legal Probabilism}}

\large Rafa\l\, Urbaniak
\end{center}


\vspace{1mm}

\thispagestyle{empty}



Legal probabilism is a research program that relies on probability theory to analyze, model and improve the evaluation of evidence and the process of decision-making in trial proceedings.  Legal probabilism remains a minority view among legal scholars, but attained greater popularity in the second half of the 20th century in conjunction with   the law and economics movement. 


 In legal cases, different lines of evidence may converge, such as two witnesses
who testify that the defendant was seen at the crime scene, or they may diverge, such as a witness who asserts the defendant was seen at the crime scene while DNA testing shows no genetic match between the defendant and the scene. Another source of complexity is that the hypotheses put forward by the parties in a trial are often complex structures of statements. 
How can different statements, and their supporting evidence, be combined and the overall prosecutor's case (or the defense's case) be put together and evaluated?

Probabilistic tools for  piecemeal evaluation of scientific evidence and spotting probabilistic fallacies in legal contexts are quite well developed. Yet, the construction of a more general probabilistic model of incorporating such evidence in a wider context of a whole case, useful for   theorizing about evidence evaluation and legal decision standards, remains a challenge.
This project intends to contribute to further development of this enterprise relying on motivations that come from different sources: formal epistemology, the development of bayesian networks, the practice of probabilistic evidence evaluation and the points raised by the critics of legal probabilism. 

The point of departure is to represent narrations  as bayesian networks enriched with additional layer of information as to which nodes correspond to evidence, and which are binary narration nodes. The key idea is that with such bayesian networks as building material, various features requested by the critics (such as coherence, resiliency, missing evidence,  explaining evidence, or ways to handle a multiplicity of proposed narrations) can be explicated in terms of corresponding properties of,  operations on, and relations between bayesian networks.   
