---
title: ""
author: ""
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - Rafal_latex6.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [LP-SEP-FINAL6.bib, munich4.bib]
csl: transactions-on-computational-logic.csl
---






```{r setup, include=FALSE}
library(ggplot2)
library(ggthemes)
knitr::opts_chunk$set(echo = TRUE)
```




\begin{center}
\large {\sc \textbf{Rekonceptualizacja probabilizmu w kontekstach prawnych}}

\large Rafa\l\, Urbaniak
\end{center}


\vspace{1mm}

\thispagestyle{empty}


Probabilism prawny to projekt badawczy, który posługuje się teorią prawdopodobieństwa do analizy, modelowania i poprawy oceny dowodów i procesów decyzyjnych w sprawach sądowych. Probabilizm prawny jest podejściem reprezentowanym przez mniejszość, ale zyskał na popularności w drugiej połowie wieku dwudziestego w powiązaniu z ruchem "prawo i ekonomia."

W sprawach prawnych, różne linie dowodowe mogą się zbiegać, jak na przykłady gdy dwoje świadków zeznaje, że widziano oskarżonego na miejscu przestępstwa, albo mogą iść w przeciwne strony, jak gdy świadkowie zeznają, iż widzieli oskarżonego na miejscu przestępstwa, ale test DNA pokazuje że nie ma zgodności między oskarżonym a materiałem z miejsca przestępstwa. Innym źródłem złożoności jest to, że hipotezy wysuwane przez różne strony mają nieraz dość złożoną strukturę. W jaki sposób rozmaite stwierdzenia i dowody je wspierające powinny być składane w jedność i oceniane?

Probabilistyczne narzędzia fragmentarycznej oceny dowodów naukowych i narzędzia pomagające dostrzegać błędy probabilistyczne są całkiem dobrze rozwinięte. Jednakże, konstrukcja bardziej ogólnego modelu umieszczającego takie dowody w szerszym kontekście całej sprawy, przydatnego dla teoretyzowania o ocenie dowodów i stadnardach dowodowych, pozostaje wyzwaniem. Projekt zamierza przyczynić się do dalszego rozwoju tego przedsięwzięcia polegając na motywacjach pochodzących z różnych źródeł: epistemologii formalnej, rozwoju sieci bayeisańskich, praktyki oceny dowodów probabilistycznych i zastrzeżeń sformułowanych przez krytyków probabilizmu prawnego.




Punktem wyjścia będzie reprezentacja narracji za pomocą sieci bayesiańskich z dodatkowymi informacjami na temat tego, które elementy odpowiadają dowodom, a które narracjom. Kluczowy pomysł polega na tym, że budując na takich sieciach można wyeksplikować różne własności narracji wymagane prez krytyków (takie jak koherencja, odporność, brakujące dowody, wyjaśnianie dowodów, czy sposoby radzenia sobie z mnogością proponowanych narracji).

