---
title: "Rethinking legal probabilism"
author: "Rafał Urbaniak"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - Rafal_latex6.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: LP-SEP-FINAL6.bib
csl: apa-5th-edition.csl
---




```{r setup, include=FALSE}
library(ggplot2)
library(ggthemes)
knitr::opts_chunk$set(echo = TRUE)
```





\tableofcontents

\thispagestyle{empty}

# Scientific goal

<!-- (description of the problem to be solved, research questions and hypotheses) -->



\todo{define legal proabilism, talk about piecemeal evaluation vs incorporation?}


As many miscarriages of justice indicate, scientific evidence is easily misinterpreted in court. This happens partially due to miscommunication  between the parties involved, but also because incorporating scientific evidence in the context of a whole case can be really hard.  For this reason, methods are needed to  support proper assessment of evidence in such contexts.


The assessment of evidence in the court of law can be viewed from at least three  perspectives: as an interplay of arguments, as an assessment of  probabilities involved, or as an interaction of competing narrations. Each  perspective presents an account of   legal reasoning [@di2018evidential; @vanEemeren2017]. Individually, each of these strains has been investigated. The probablistic approach is the most developed one, but a probabilistic approach to the incorporation of scientific evidence in the context of a whole case is still underdeveloped. This is partially so in light of various lines of criticism developed by the representatives of the other strains, as ,  the criticism of the probabilistic approach present in the literature have not been satisfactorily adressed by the proponents of legal probablism.


The \textbf{goal of this project} is to contribute to the \textbf{development of legal probabilism}  by formulating its variant that  accomodates important \textbf{insights provided by its critics}. A crucial point of criticism is that the fact-finding process  should  be conceptualized as \textbf{a competition of narrations}. I plan to develop methods that allow the probabilist to take this perspective, and explain how such methods allow the legal probabilist to address various other objections present in the literature. The key idea is that once  \textbf{narrations are represented as bayesian networks, various criteria on,  features of  and operations on narrations can be explicated in terms of corresponding properties of and operations on bayesian networks}. The conceptual developments are accompanied by  technical accounts. \textbf{\textsf{R}} code  capturing to the technical features developed is made available to the reader.   Thus, the output will be a \textbf{unifying extended probabilistic model embracing key aspects of the narrative and argumentative approaches, susceptible to AI implementation.}  The methods employed include: Bayesian statistical methods (including Bayesian approach to higher-order probability), imprecise probabilities and Bayesian networks.






# Significance 



(state of the art, justification for tackling a specific scientific problem,
justification for the pioneering nature of the project,
the impact of the project results on the development of the research field and scientific discipline);


## State of the art


From among the three perspectives mentioned in the beginning, I focus on the probablistic approach and take it as my point of departure, for various reasons:

- The project is to be informed by and reflect on the actual practice of legal evidence evaluation, and much of  scientific evidence in such contexts  has probabilistic form.

- Probabilistic tools are fairly well-developed both for applications and within formal epistemology, reaching a state of fruition which I think should inspire deeper reflection.

- Statistical computing tools for such methods are avaialable, which makes programming development and preliminary evaluation of the ideas to be defended a viable enterprise. 



Alas,  while probabilistic tools for  piecemeal evaluation of scientific evidence in legal contexts are well developed, the construction of a more general probabilistic model of incorporating such evidence in a wider context of a whole case, and probabilistic explication of legal decision standards, remain a challenge.


One important difficulty is that there are various thought experiments in which the probability of guilt is very high and yet conviciton or finding of liability is intuitively unjustified---these are known as  proof paradoxes [@Cohen1977The-probable-an; @redmayne2008exploring]. \todo{Add an example}


At least \emph{prima facie}, then, it seems that some conditions other than high posterior probability of liability have to be satisfied for the decision to penalize (or find liable) to be justified.  Accordingly, various informal notions  have been claimed to be essential for  a proper explication of judiciary decision standards [@wells1992naked; @haack2011legal]. For instance,  evidence is claimed to be insufficient for conviction if it is not \emph{sensitive} to the issue at hand: if it remained the same even if the accused was innocent [@enoch2015sense]. Or, to look at another approach,  evidence is claimed to be insufficient for conviction if it doesn't \emph{normically support} it: if---given the same evidence---no explanation would be needed even if the accused was innocent [@Smith_conviction_mind_2017].   A legal probabilist needs either to show that these notions are  unnecessary or inadequate for the purpose at hand, or to indicate how they can be explicated in probabilistic terms. 




\todo{describe what the probabilistic model is before we get deeper?}

Another point of criticism of the wider proabilist model, legal proceedings are back-and-forth between opposing parties in which  cross-examination is of crucial importance,  reasoning goes not only evidence-to-hypothesis, but also hypotheses-to-evidence [@wells1992naked; @allen2007problematic] in a way that seems analogous to inference to the best explanation [@dant1988gambling], which notoriously is claimed to not be susceptible to probabilistic analysis [@Lipton2004-LIPITT].   An informal philosophical account inspired by such considerations---The \textbf{No Plausible Alternative Story (NPAS)} theory [@allen2010no]---is that the courtroom is a confrontation of competing narrations [@wagenaar1993anchored; @ho2008philosophy] offered by the sides, and  the narrative to be selected should be the most plausible one. The view is conceptually plausible [@di2013statistics], and  finds  support  in psychological evidence [@pennington1991cognitive; @pennington1992explaining]. 



It would be a great advantage of legal probabilism if it could to model phenomena captured by the narrative approach, but how is the legal probabilist to make sense of them?  From her perspective,  the key disadvantage of NPAS is that it abandons the rich toolbox of probabilistic methods and takes the key notion of plausibility to be a primitive notion which should be understood only intuitively. 
 
 
 
Initial philosophical analysis of the approach has been performed, [@di2013statistics]  pioneering a probabilistic understanding of narrations. 

\todo{add more about Marcello}



## Choice of problem



## Pioneering nature \& impact



# Concept and work plan 

(general work plan, specific research goals,
results of preliminary research, risk analysis);

# Research methodology

(underlying scientific methodology, methods, techniques and research tools,
methods of results analysis, equipment and devices to be used in research);


# References



