---
title: "Boosting Legal Probabilism  (or Beyond Legal Probabilism 1.01)"
author: "Marcello Di Bello and Rafal Urbaniak"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - Rafal_latex4.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 10pt
documentclass: scrartcl
urlcolor: blue
bibliography: [../references/referencesMRbook.bib]
csl: apa-5th-edition.csl
---



# The Book

## Brief Description 

\footnotesize In one or two paragraphs, describe the work, including its rationale, approach, and pedagogy. (This book is... It does... Its distinguishing features are...)

\normalsize

Legal probabilism (roughly) is a research program that relies on probability theory to analyze, model and improve the evaluation of evidence and the process of decision-making in trial proceedings. This book boosts legal probabilism to its limits.\todo{This sounds a bit too much, say something less boasty?} We first examine the simpler version of the theory, legal probabilism 1.01, which falls prey to several difficulties, including the problem of conjunction, puzzles of naked statistical evidence, the problem of priors. We show that these difficulties cannot be addressed within the limited framework of legal probabilism 1.01. We then develop a more sophisticated version of the theory, legal probabilism 1.02, which deploys Bayesian networks and seminal ideas in the literature in forensic science and artificial intelligence. 'Boosting Legal Probabilism' articulates the first comprehensive philosophical analysis of whether---and if so, to what extent---legal probabilism 1.02 can overcome the limitations of legal probabilism 1.01. We show that the more sophisticated version significantly improves on the simpler version and rivals in explanatory power two competing accounts of judicial fact-finding: argumentation theory and relative plausibility. To add precision to the claims made in the book, the analytical argument is supplemented with an \textbf{\textsf{R}} code implementation.  


'Boosting Legal Probabilism' is aimed at philosophers with an interest in legal epistemology and epistemology more generally. Many of the difficulties of legal probabilism resemble difficulties faced by Bayesianism in epistemology. The book will also draw attention outside philosophy from legal scholars who have championed applications of probability theory to evidence law as well as scholars who have resisted this trend. Another target audience includes computer scientists and psychologists interested in studying evidential reasoning and decision-making under uncertainty. Besides contributing to the literature about legal probabilism, the book aims to introduce unfamiliar readers to the rich interdisciplinary debate on the topic, often scattered throughout journals and books in philosophy, law, computer science, forensic science and psychology. So the book is aimed at scholars, advanced undergraduates and curios readers more generally. Some chapters present original research and require technical background in probability theory. Others are introductory, suitable for an advanced undergraduate course.





 

 


## Outline 

\noindent
\textbf{Part I}

\noindent
The first part of the book outlines legal probabilism 1.01 (Chapter 1) 
and its foes (Chapter 2). The 1.01 version comprises 
a familiar repertoire: Bayes' theorem, 
likelihood ratios, probability thresholds, expected utility 
maximization. This repertoire has proven useful in several ways, 
especially in the assessment of explicitly quantitative evidence 
such as DNA matches and other expert evidence. At the same time, 
legal probabilism 1.01 is liable to a host of conceptual difficulties: 
the conjunction problem, the problem of priors, paradoxes of naked statistical evidence. 
These difficulties are well-known. Others are less familiar: 
the problem of complexity, soft variables, the difficulty with corroboration. 

Part I is meant to instill interest in the topic among unfamiliar readers and refresh seasoned readers 
about the main points of contention. Part I provides the essential background for a 
deeper examination of legal probabilism 1.01 and the development of its 
more sophisticated version. The remaining two parts of the book covers evidence assessment (Part II)
and decision-making (Part III). This distinction reflects the fact that legal probabilism is both a theory 
of evidence assessment (or evidence evaluation, evidence weighing) 
as well as a theory of decision-making at trial. These two facets are 
best kept separate for analytical clarity. 

\vspace{3mm}
\noindent
\textbf{Part II}

\noindent
The second part of the book discusses in great detail three formal 
tools used for the assessment of evidence from a probabilistic 
perspective: Bayes' theorem, likelihood ratios and Bayesian networks. 
This parts also discusses how these formal tools can 
be used in assessing evidence at trial as well as what 
their limitations are. 

Chapter 3 presents Bayes' theorem and weighing one 
or two pieces of evidence. This approach is useful in many ways, for example, to avoid reasoning 
fallacies such as the prosecutor's fallacy and base rate fallacy. The limitations of this approach
are discussed in Chapter 4. Most importantly, court cases often require fact-finders to weigh several pieces 
of evidence, sometimes conficting and susceptible to different interpretations. The hypotheses 
that the fact-finders are asked to evaluate in light of the evidence presented are structured stories 
or explanations of the evidence constituted by several sub-propositions. This level of complexity 
can hardly be modeled by a simple application of Bayes' theorem. A more sophisticated 
machinery for evidence assessment is nedded. 

Before discussing this more sophisticated machinery, 
the book describes an approach that is, in some important way, an alternative to Bayes' theorem and 
that many legal probabilists 
have found useful: likelihood ratios. Bayes' theorem requires 
prior probabilities, and assessing  prior probabilities 
is notoriously difficult. A simpler method only uses likelihood ratios. While this approach is 
still unable to model complex bodies of evidence, it has proven useful in many ways. 
Chapter 5 describes, in great detail, the likelihood approach, its application 
and stregthens in asessing evidence at trial. Cold-hit DNA matches 
are used an illustration. The chapter also examines the 
weakeesses of the likelihood approach, specifically, the choice of the competing 
hypotheses to be compared in the likelihood ratio can be a source of confusion, 
manipulation and subjective judgment. 


Chapters 3, 4 and 5 -- combined -- show that we need to move past legal 
probabilism 1.01. This task is accomplished in Chapters 6 through 10. To this end, we focus 
on two broad theoretical shortcomings of legal probabilism 1.01: first, its inability to represent complex relationships 
between pieces of evidence, such as undercutting, rebutting, converging, corroborating evidence; second, its inability to capture the fact that judges and jurors often think holistically about the evidece, say in terms of stories or explanations, without assessing the evidence by discrete applications of Bayes' theorem. We show that legal probabilism 1.02 -- roughly, legal probabilism 1.01 supplemented by Bayesian networks (Chapter 6) -- can represent complex 
relantionships between pieces of evidence (Chapters 7 and 8), as well 
as notions such as explanatory coherence (Chapter 9 and 10). As a consequence, 
legal probabilism 1.02 rivals two competing accounts of judicial fact-finding: 
argumentation theory and relative plausibility.





\vspace{3mm}
\noindent
\textbf{Part III}

\vspace{3mm}
\noindent
\textbf{Table of contents}

\renewcommand{\labelenumi}{\Roman{enumi}}
\renewcommand{\labelenumii}{\arabic{enumii}}
\renewcommand{\labelenumiii}{\arabic{enumii}.\arabic{enumiii}}

\begin{enumerate}
\item Legal probabilism 1.01 and its foes
\begin{enumerate}

  \item The emergence of legal probabilism
  \begin{enumerate}
  \item  Famous cases
  \item  Probabilistic evidence
  \item  Trial by mathematics
  \item  Some history
  \end{enumerate}
  

  
  \item  A skeptical perspective
  \begin{enumerate}
  \item  The difficulty about conjunction
  \item  The problem of priors
  \item  Naked statistical evidence
  \item  The complexity problem
  \item  Soft variables
  \item  Corroboration
  \item  The reference class problem
  \item  Non-probabilistic theories
  \end{enumerate}


\end{enumerate}
\item  Evidence assessment


\begin{enumerate}


\setcounter{enumii}{2}
  \item  Bayes' Theorem and the usual fallacies
  \begin{enumerate}
  \item  Assuming independence
  \item  The prosecutor's fallacy
  \item  Base rate fallacy
  \item  Defense attorney's fallacy
  \item  Uniqueness fallacy
  \item  Case studies
  \end{enumerate}

  
  
  \item  Complications and caveats
  \begin{enumerate}
  \item  Complex hypotheses and complex bodies of evidence
  \item Source, activity and offense level hypotheses
  \item  Where do the numbers come from?
  \item  Modeling corroboration
  \item  Stories, explanations and coherence
  \end{enumerate}

  
  \item  Likelihood Ratios and Relevance
  \begin{enumerate}
  \item Likelihood ratio as a measure of evidence strength
  \item The risk of false positive and its impact
  \item Hypothesis choice
  \item Levels of hypotheses and the two-stain problem
  \item Relevance and the small-town murder scenario
  \item The cold-hit confusion
  \item  Likelihood ratio and  cold-hit DNA matches
  \end{enumerate}



  \item  Bayesian Networks
  \begin{enumerate}
  \item  Bayesian networks to the rescue
  \item  Legal evidence idioms
  \item Scenario idioms
  \item Modeling relevance
  \item  Case study: Sally Clark
  \item DNA evidence
  \end{enumerate}
  
  \item Conflicts
  \begin{enumerate}
  \item Argumenation theory
  \item Undercutting and rebutting evidence
  \item Cross-examination
  \item Conflicting evidence in Bayesian networks
  \end{enumerate}
 
 
  \item Corroboration
  \begin{enumerate}
  \item Boole's formula and Cohen's challenge
  \item  Modeling substantial rise in case of agreement
  \item Ekel\"of's corroboration measure and evidentiary mechanisms
  \item General approach with multiple false stories and multiple witnesses
  \end{enumerate}


  \item Coherence
  \begin{enumerate}
  \item  Existing probabilistic coherence measures
  \item  An array of counterexamples
  \item Coherence of structured narrations with Bayesian networks
  \item  Application to legal cases
  \end{enumerate}

  \item  New legal probabilism
    \begin{enumerate}
    \item  Desiderata
    \item  A probabilistic framework for narrations
    \item  Probabilistic explications of the desiderata
    \item  Bayesian network implementation
    \end{enumerate}


\end{enumerate}
\item  Trial Decisions
\begin{enumerate}



\setcounter{enumii}{10}
  \item  The functions of the proof standards
  \begin{enumerate}
  \item  Conceptual desiderata
  \item  Protecting defendants
  \item  Error reduction and error distribution/allocation
  \item  Dispute resolution and public deference
  \item  Justification and answerability
  \end{enumerate}



  \item  Standards of proof
  \begin{enumerate}
  \item  Legal background
  \item  Probabilistic thresholds
  \item  Theoretical challenges
  \item  Specific narratives
  \item The comparative strategy
  \item  The likelihood strategy
  \item Challenges (again)
  \item Probabilistic thresholds revised
  \item  Bayesian networks and probabilistic standard of proof
  \end{enumerate}

  \item  Accuracy and the risk of error
  \begin{enumerate}
  \item  Minimizing expected costs
  \item  Minimizing expected errors
  \item  Expected v.\ actual errors
  \item  Competing accounts of the risk of error
  \item  Bayesian networks and the risk of error
  \end{enumerate}



  \item  Fairness in trial decisions
  \begin{enumerate}
  \item  Procedural v.\ substantive fairness
  \item  Competing measures of substantive fairness
  \item  Bayesian networks and fairnesss
  \end{enumerate}


  \item  Alternative accounts and legal probabilism
  \begin{enumerate}
  \item  Baconian probability
  \item  Relative Plausibility
  \item  Arguments
  \item  Sensitivity
  \item  Normic Support
  \item  Justification/foundherentism
  \item  Completeness
  \item  Relevant alternatives
  \item  Knowledge
  \end{enumerate}

\item Conclusions
\end{enumerate}
\end{enumerate}


## Outstanding Features of the Book 

- (First) comprehensive sustained philosophical discussion of legal probabilism.

- Multi-faceted in its incorporation of insights from various discussions present in legal, philosophical, and forensic  research.

- With a practical accent, due to the  implementation of the conceptual points by means of bayesian networks and \textbf{\textsf{R}} programming language. 

\todo{what else?}


## Apparatus

\footnotesize a. Will the book include photographs, line drawings, cases, questions, problems, glossaries, bibliography, references, appendices, etc.?

\vspace{2mm}

\normalsize 

Yes, the book will contain various plots, either of Bayesian networks, or some other data visualisations generated by `ggplot2`.  The book also will contain bibliography. 
\vspace{2mm}

\footnotesize b. If the book is a text, do you plan to provide supplementary material to accompany it? (Teacher's manual, study guide, solutions, answers, workbook, anthology, or other material.)

\vspace{2mm}

\normalsize

The book will be accompanied by an  online-only appendix detailing the use of the `R` code in the book and the source code we used. 



## Competition


\footnotesize a. Consider the existing books in this field and discuss specifically their strengths and weaknesses. Spell out how your book will be similar to, as well as different from, competing works.


\todo{For now, let's list competition, and discuss key differences}

\normalsize 

Three types: BNs in the law, Philosophy \& law, Statistics in law and forensics

- “Bayesian Networks and Probabilistic Inference in Forensic Science” by Taroni, Aitken, Garbolino and Biedermann. 

- “Risk Assessment and Decision Analysis with Bayesian Networks” by Fenton and Neil.


- “Bayesian Networks With Examples in R” by Marco Scutari and Jean-Baptiste Denis.


- Alex Stein, foundations of evidence law

- Nance, Burdens of proof

- Schauer, Profiles, \dots

- Ho, Philosophy of evidence law

- Robertson, Vignaux

- Lucy Dawid, 

- Statistics for Lawyers etc.

b. Consider what aspects of topical coverage are similar to or different from the competition. What topics have been left out of competing books and what topics have been left out of yours?

c. Please discuss each competing book in a separate paragraph. (If possible, please provide us with the publisher and date of publication as well.) This information will provide the reviewers and the publisher a frame of reference for evaluating your material. Remember, you are writing for reviewers and not for publication, so be as frank as possible regarding your competition. Give credit where credit is due, and show how you can do it better.

# Market Considerations

## The Primary Market

1. What is the major market for the book? (Scholarly/professional, text, reference, trade?)

2. If this is a text, for what course is the book intended? Is the book a core text or a supplement? What type of student takes this course? What is the level? (Major or non-major; freshman, senior, graduate?) Do you offer this course yourself? If so, how many times have you given it? Is your text class-tested?

3. If the market is scholarly/professional, reference, or trade, how may it best be reached? (Direct mail, relevant journals, professional associations, libraries, book or music stores?) For what type of reader is your book intended?


# Status of the Work


1. Do you have a timetable for completing the book?
 
  a. What portion or percentage of the material is now complete?
 
 b. When do you expect to have a complete manuscript?
 
2. What do you estimate to be the size of the completed book?

a. Double spaced typewritten pages normally reduce about one-third when set in type; e.g., 300 typewritten pages make about 200 printed pages. There are about 450 words on a printed page.


b. Approximately how many photographs do you plan to include?


c. Approximately how many line drawings (charts, graphs, diagrams, etc. ) will you need?

d. Do you plan to include material requiring permission (text, music, lyrics, illustrations)? To what extent? Have you started the permissions request process?


3.  Do you plan to class-test the material in your own or other sections of the course? (Any material distributed to students should be protected by copyright notice on the material.)


# Sample Chapters

Select one or two chapters of the manuscript that are an integral part of the book. They should be those you consider the best-written ones, and do not have to be in sequence. For example, you might submit chapters 3, 7, and 14 of a 20-chapter book, so long as these chapters represent the content and reflect your writing style and pedagogy in the best possible light. It is also advisable to submit any chapter that is particularly innovative or unique. Sample chapters should contain rough sketches, charts, hand-written musical examples or xerox reproductions, and description of photographs to be included. The material need not be in final form, although it should be carefully prepared and represent your best work. In your preparation, emphasis should be on readability. Please do not bind your manuscript, as we will have to unbind it in order to make photocopies for reviewers. Also be sure all pages are numbered either consecutively or double-numbered by chapter.

# Reviews

If we are interested in your project, we will commission outside reviewers to read and evaluate your proposal. We will, of course, obtain the best available reviewers to consider your work. If you wish to suggest the names of experts in your field whom you believe to be ideally suited to evaluate your proposal, you may provide their names, titles, and email addresses. While we are unlikely to approach these scholars to act as reviewers themselves, we may ask them for their suggestions for peer readers. Naturally, we do not reveal the names of reviewers without their permission.

# Author Background

Please include a current CV or brief biography of your writing, teaching, and/or educational background and experience. Be sure to list any books that you have previously published, and any other information about yourself on why you are qualified to write this book.

# Response Time

Please allow at least 6-10 weeks for the manuscript proposal evaluation and review process. We will contact you as soon as we have had a chance to thoroughly examine your manuscript proposal. Thank you for your interest in Oxford University Press. We look forward to reading your materials.