---
title: "Key Ideas for LP Book"
author: "Marcello"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - style.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [/Users/mdibello/Desktop/Book-Legal-Prob/references/referencesMRbook.bib]
csl: [/Users/mdibello/Desktop/Book-Legal-Prob/references/apa-6th-edition.csl]
indent: true
---


\paragraph*{Not just high probability} Legal probabilism, in the simple version, focuses on the probability of liability as the main criterion for trial decision-making. If this probability is sufficiently high, the decision should be against the defendant, and otherwise it should favor the defendant. 

But other dimensions (should) guide decision-making and they might not be reducible to the probability of liability. Some of these other dimensions are:

- How certain are we about the probability of liability? (Higher-order uncertainty) 

- How good (specific, coherent, plausible, explanatory powerful) is the story presented?

- Did the defense challenged the other party's story? Did the story survive the challenges?

- Is any evidence missing?


A more sophisticated version of legal probabilism, then, should be able to 
do at least two things: first, formally model these additional dimension using the language of probability (or determine to what extent they fall outside the scope of probability theory and cognate theories); and second, show why relying on these additional dimensions in decision-making do foster important values, such as the accuracy and fairness of trial decisions.

\vspace{10mm}
\noindent
So we can envision  four central chapters: 

\paragraph*{Chapter: Higher-order probability} See existing chapter and paper on higher-order legal probabilism.

\paragraph*{Chapter: Narratives, specificity, coherence etc.} See Rafal's paper 
on coherence. 

\paragraph*{Chapter: Cross-examination and arguments} See Marcello's paper on cross-examination and Bayesian networks, and also paper on awareness growth and Bayesian networks.

\paragraph*{Chapter: Gaps in Evidence} See existing paper on gaps in the evidence.




\vspace{10mm}
\noindent
This more sophisticated version of 
legal probabilism should answer some of existing challenges to 
simple legal probabilism. 


\paragraph*{Challenge 1: We do not have the numbers} Many critics of legal probabilism 
complaint that it is difficult to find all the numbers required  by the probability 
tables of a Bayesiaan network. So, then, often these numbers are inserted 
as guess work, educated guesses or simply becaue they cannot be left blank.
\textit{Unclear where our book will address this challange. Use comparative probability? } 

\paragraph*{Challenge 2: Evidence is evaluated holistically}. \textit{The chapter 
on story coherence should address this challange.} 


\paragraph*{Challenge 3: Learning isn't updating} Ronald Allen complains that Bayesian updating isn't an adequate model 
of what goes on in the courtroom when evidence is presented. The decision-makers do not start from priors and update them based on the pieces of evidence presented. What happens is more complicated and cannot be modeled by Bayesian updating. 
\textit{The chapter 
on cross-examination and arguments should address this challange.} 

\paragraph*{Challenge 4: Trials are adversarial} Trials are often adversarial. Evidence is examined and cross-examined. 
How can this adversarial process be modeled probabilistically?
\textit{The chapter on cross-examination and arguments should address this challange.} 


\paragraph*{Challenge 5: No evidence that probability reduces errors} It is clear that people make probabilistic mistakes in reasoning, but does this show that mistaken convictions are caused by these probabilistic mistakes? There is no evidence of that. In what way does probability actually improve the accuracy of legal decisions?
\textit{Discussion about accuracy and fairness should address this challange}


















