---
title: "Awareness Growth in Bayesian Networks"
subtitle: "Reply to Steele and Stefánsson"
author: "Marcello/Rafal"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - style.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [/Users/mdibello/Desktop/Book-Legal-Prob/references/referencesMRbook.bib]
csl: [/Users/mdibello/Desktop/Book-Legal-Prob/references/apa-6th-edition.csl]
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

Learning is modeled in the Bayesian framework by the rule of conditionalization. 
This rule posits that the agent's new degree of belief in a proposition $H$ 
after a learning experience $E$ should be the same as the agent's old degree 
of belief in $H$ conditional on $E$. That is, 
\[\ppr{E}{H}=\pr{H \vert E},\]
where $\pr{}$ represents the agent's old degree of belief (before the learning experience $E$) 
and $\ppr{E}{}$ represents the agent's new degree of belief (after the learning experience $E$).

<!---One assumption here is that $E$ is learned with certainty. After the agent learns about $E$, there 
is no longer any doubt about the truth of $E$. This assumption has been the topic of extensive discussion in the literature.^[As is well-known, Jeffrey's conditionalization relaxes this assumption.] The other assumption---which we focus on here---is that $E$ and $H$ belong to the agent's algebra of propositions.
This algebra models the agent's awareness state, the propositions that the agent entertains as live possibilities. --->

Both $E$ and $H$ belong to the agent's algebra of propositions.
This algebra models the agent's awareness state, the propositions taken to be live possibilities.   Conditionalization never modifies the algebra and thus makes it impossible for an agent to learn something they have never thought about. This forces a great deal of rigidity on the learning process. Even before learning about $E$, the agent must already have assigned a degree of belief to any proposition conditional on $E$. This picture commits the agent to the specification of their 'total possible future experience' (Howson 1976, The Development of Logical Probability), as though learning was confined to an 'initial prison' (Lakatos, 1968, Changes in the Problem of Inductive Logic).  

But, arguably, the learning process is more complex than what conditionalization allows. 
Not only do we learn that some propositions that we were entertaining 
are true or false, but we may also learn new propositions that we did not entertain before.  Or we may entertain new propositions---without necessarily learning that they are true or false---and this change in awareness may in turn change what we already believe. How should this more complex learning process be modeled by Bayesianism? Call this the problem of awareness growth.
<!---This problem can perhaps be divided into two parts: (i) how to model \textit{learning} a new proposition not in the initial awareness state of the agent;  (ii) how to model \textit{entertaining} a new proposition not in the initial awareness state of the agent (without yet learning it). 
--->

Critics of Bayesianism and sympathizers alike have been discussing the problem of awareness growth under 
different names for quite some time, at least since the eighties. This problem arises in a number 
of different contexts, for example, new scientific theories (Glymour, 1980, Why I am not a Bayesian; Chihara 1987, Some Problems for Bayesian Confirmation Theory; Earmann 1992, Bayes of Bust?), language changes
 and paradigm shifts (Williamson 2003, Bayesianism and Language Change), and theories of induction (Zabell, Predicting the Unpredictable).

<!---Now, of course, the algebra of propositions could in principle be so rich 
to contain anything that could possibly be conceived, expressed, thought of. 
Such an algebra would not need to change at any point in the future. God-like agents could be associated with such rich algebra of propositions, but this is hardly a plausible model of ordinary agents with bounded resources such as ourselves. A fully comprehensive algebra of propositions cannot be the answer here.
--->

A proposal that has attracted considerable scholarly attention is Reverse Bayesianism (Karni and Viero, 2015, Probabilistic Sophistication and Reverse Bayesianism; Wenmackers and Romeijn 2016, New Theory About Old Evidence; Bradely 2017, Decision Theory with A Human Face) . The idea  is to model awareness growth as a change in the algebra while ensuring that the probabilities of the propositions shared between the old and new algebra remain fixed under suitable constraints.  

Let $\mathcal{F}$ be the initial algebra of propositions and let $\mathcal{F}^+$ the algebra after the agent's awareness has grown.  Both contain the contradictory proposition $\perp$ and tautologous proposition $\top$ and they are closed under connectives such as disjunction $\vee$, conjunction $\wedge$ and negation $\neg$. Denote by $X$ and $X^+$ the subsets of these algebras that contain only basic propositions, those without connectives. <!---Since   $\mathcal{F}\subseteq \mathcal{F}^+$, then also $X\subseteq X^+$. --->  \textbf{Reverse Bayesianism} posits that the ratio of probabilities for any basic propositions $A$ and $B$ in both $X$ and $X^+$---the basic propositions shared by the old and new algebra---remain constant through the process of awareness growth:
\[\frac{\pr{A}}{\pr{B}} = \frac{\ppr{+}{A}}{\ppr{+}{B}},\] 
where $\pr{}$ represents the agent's degree of belief before awareness growth 
and $\ppr{+}{}$ represents the agent's degree of belief after awareness growth.

<!---What is the justification for Reverse Bayesianism? Perhaps the best justification is pragmatic. --->
Reverse Bayesianism is an elegant theory that manages to cope with a seemingly intractable problem. 
As the awareness of an an agent grows, the agent would prefer not to throw away completely the epistemic work they have done so far. The agent may desire to retain as much of their old degrees of beliefs as possible. Reverse Bayesianism provides a simple recipe to do that. It also coheres with the conservative spirit of  conditionalization which preserves the old probability distribution conditional on what is learned. <!--- Reverse Bayesianism preserves the old probability distribution conditional on the old awareness state.^[Strictly speaking, this interpretation is what we later call Awareness Rigidity.] Similarly, conditionalization \textbf{SHOW PICTURE BELOW}.--->

Unfortunately, Reverse Bayesianism is not without complications. Steele and Stefánsson (2021, Belief Revision for Growing Awareness) argue that Reverse Bayesianism, when suitably formulated, can work in a limited class of cases, what they call \textit{awareness expansion}, but cannot work for \textit{awareness refinement} (more on this distinction later). Their argument rests on a number of ingenious counterexamples. 

We contend, however, that their counterexamples have limited applicability and thus constitute an overall weak argument against Reverse Bayesianism (\S \ \ref{sec:counterexamples}). Still, we share Steele and Stefánsson's skepticism and provide a better counterexample (\S \ \ref{sec:better}). At the same time, we carve out a class of cases in which Reverse Bayesianism still holds, and these include not just cases of expansion but also some cases of refinement (\S \ \ref{sec:downstream}). Our critique of Reverse Bayesianism is thus more fine-grained than Steele and Stefánsson's. Ultimately, we conjecture that the problem of awareness growth cannot be tackled in an algorithmic manner because subject-matter structural assumptions are necessary (\S \ \ref{sec:material}). We rely on the theory of Bayesian networks at several key junctures in our argument. 


# Counterexamples?
\label{sec:counterexamples}

We begin by rehearsing two of the ingenious counterexamples to Reverse Bayesianism 
by Steele and Stefánsson. One targets awareness expansion and the other awareness refinement. The difference between expansion and refinement is intuitively plausible, but it can be tricky to pin down formally. A rough characterization will suffice here. Suppose, as is customary, propositions are interpreted as sets of possible worlds, where the set of all possible worlds is the possibility space. An algebra of propositions thus interpreted induces a partition of the possibility space. Refinement occurs when the new proposition added to the algebra induces a more fine-grained partition of the possibility space. Expansion, instead, occurs when the new proposition shows the existing partition of the possibility space is not exhaustive.

The first counterexample by Steele and Stefánsson targets 
cases of awareness expansion:

> \textsc{Friends}: Suppose you happen to see your partner enter your best friend’s house on an evening when your partner had told you she would have to work late. At that point, you become convinced that your partner and best friend are having an affair, as opposed to their being warm friends or mere acquaintances. You discuss your suspicion with another friend of yours, who points out that perhaps they were meeting to plan a surprise party to celebrate your upcoming birthday—a possibility that you had not even entertained. Becoming aware of this possible explanation for your partner’s behaviour makes you doubt that she is having an affair with your friend, relative, for instance, to their being warm friends. (Steele and Stefánsson, 2021, Section 5, Example 2)

\noindent
<!---Why does the scenario \textsc{Friends} conflict with Reverse Bayesianim? --->
<!---Even though Steele and Stefánsson do not provide the details, it pays to be explicit here at the cost of pedantry. --->
Initially, the algebra only contains the hypotheses 'my partner and my best friend met to have an affair' (\textit{Affair}) and 'my partner and my best friend met as friends or acquaintances' (\textit{Friends/acquaintances}). The other proposition in the algebra is the evidence, that is, the fact that your partner and your best friend met one night without telling you (\textit{Secretive}). <!---There may be other propositions, but these are the ones to focus on. Hypothesis \textit{Affair} better explains the evidence at your disposal than hypothesis \textit{Friends/acquaintances}. In probabilistic terms, this can be expressed by
comparing likelihoods:--->
<!---\[\pr{ \textit{Secretive} \vert \textit{Affair}}> \pr{\textit{Secretive} \vert \textit{Friends/acquaintances}},\]--->
<!---from which it also follows that --->
Given this evidence, \textit{Affair} is more probable than \textit{Friends/acquaintances}:
\[\pr{\textit{Affair} \vert  \textit{Secretive} }> \pr{\textit{Friends/acquaintances} \vert \textit{Secretive}} \tag{>}.\]
<!---so long as the prior probabilities of the two hypotheses are not skewed in one direction.^[If you were initially nearly certain your partner could not possibly have an affair, even the fact they behaved very secretively or lied to you might not affect the probability of the two hypotheses.] --->
When the algebra changes, a new hypothesis is added which you had not considered before: your partner and your best friends met to plan a surprise party for your upcoming birthday (\textit{Surprise}). <!---The evidence
\textit{Secretive} now makes  better sense in light of this new hypothesis than the hypothesis \textit{Affair}.--->
<!--\[\ppr{+}{ \textit{Secretive} \vert \textit{Surprise}}> \ppr{+}{\textit{Secretive} \vert \textit{Friends/acquaintances}}\]--->
<!---\[\ppr{+}{ \textit{Secretive} \vert \textit{Surprise}}> \ppr{+}{\textit{Secretive} \vert \textit{Affair}}.\]--->
Given the same evidence, \textit{Friends/acquaintances} is now more likely than \textit{Affair}:^[This holds assuming (a) that hypothesis \textit{Surprise} is more likely than the hypothesis \textit{Affair}:
<!---\[\ppr{+}{ \textit{Surprise} \vert \textit{Secretive}}> \ppr{+}{ \textit{Friends/acquaintances} \vert \textit{Secretive} }\]--->
\[\ppr{+}{ \textit{Surprise} \vert \textit{Secretive}}> \ppr{+}{ \textit{Affair} \vert \textit{Secretive}},\]
and in addition, (b) that \textit{Surprise} implies \textit{Friends/acquaintances}. After all, in order to prepare a surprise party, your partner and best friend have to be at least acquaintances.]
\[\ppr{+}{\textit{Affair} \vert  \textit{Secretive} } < \ppr{+}{\textit{Friends/acquaintances} \vert \textit{Secretive}}. \tag{<}\]
The conjunction of ($>$) and ($<$) violates Reverse Bayesianism. 




<!----Reverse Bayesianism is not yet in trouble. Steele and Stefánsson, however, 
conclude that the probability of \textit{Friends/acquaintances} should now exceed that of
\textit{Affair}. They write: 'Becoming aware of this possible explanation for your partner’s behaviour makes you doubt that she is having an affair with your friend, relative, for instance, to their being warm friends.' So: --->
<!---Arguably, this holds because --->
<!---So, if \textit{Surprise} is more likely than \textit{Affair} (by $*$), then --->

<!---
A lot hinges in this example on how we understand hypothesis \textit{Friends/acquaintances}. For one thing,  In other hand, one might argue that, as awareness grows, the meaning of the hypothesis \textit{Friends/acquaintances} has effectively changed. Initially, this hypothesis did not include the possibility that they would organized a surprise party and then later it came to include this possibilities. Only on the first reading, the example is a genuine counterexample to reverseve Bayesianism. 
--->

But, as Steele and Stefánsson admits, Reverse Bayesianism can still be made to work with a slightly 
different---though quite similar in spirit---condition, called \textbf{Awareness Rigidity}: 
\[\ppr{+}{A \vert T^*}=\pr{A},\]
where $T^*$ corresponds to a proposition that picks out, from the vantage point of the new awareness state, the entire possibility space before the episode of awareness growth. In our running example, the proposition $\neg\textit{Surprise}$ picks out the entire possibility space in just this way. <!---So 
Awareness Rigidity would require that:
\[\ppr{+}{\textit{Friends/acquaintances} \vert \neg\textit{Surprise}}=\pr{\textit{Friends/acquaintances}}.\]
 Conditional on $\neg\textit{Surprise}$, it is indeed true that the probability of \textit{Friends/acquaintances} has not changed before and after the episode of awareness growth. 
 --->
And conditional on $\neg\textit{Surprise}$, the probability of \textit{Affair} does not change. Thus,
\[\ppr{+}{\textit{Affair} \vert  \textit{Secretive} \& \neg\textit{Surprise} } > \ppr{+}{\textit{Friends/acquaintances} \vert \textit{Secretive} \& \neg\textit{Surprise}}. \]
Awareness Rigidity is vindicated. Reverse Bayesianism---the spirit of it, not the letter---stands.

This is not the end of the story, however. Steele and Stefánsson offer another counterexample that also works against Awareness Rigidity, this time targeting a case of refinement:

  > \textsc{Movies}: Suppose you are deciding whether to see a movie at your local cinema.
You know that the movie's predominant language and genre will affect your viewing
experience. The possible languages you consider are French and German and the
genres you consider are thriller and comedy. But then you realise that, due to your
poor French and German skills, your enjoyment of the movie will also depend on the
level of difficulty of the language. Since it occurs to you that the owner of the cinema is
quite simple-minded, you are, after this realisation, much more confident that the movie
will have low-level language than high-level language. Moreover, since you associate
low-level language with thrillers, this makes you more confident than you were before
that the movie on offer is a thriller as opposed to a comedy. (Steele and Stefánsson, 2021, Section 5, Example 3)

\noindent
Initially, you did not consider language difficulty. So you assigned the same probability to the hypotheses
 \textit{Thriller} and \textit{Comedy}. 
<!---The algebra contained the propositions \textit{French} and \textit{German}, as well as \textit{Thriller} and \textit{Comedy}. <!---What you are concerned about is whether your will enjoy the movie or not (\textit{Enjoy Movie}), depending on its language and genre. ---> <!---Then, you realized another variable might be at play, namely the level of difficulty of the language of the movie.---> <!---, \textit{Difficult} and \textit{Easy}.---> But learning that the owner is simple-minded made you think the level of linguistic difficulty must be low and the movie most likely a thriller rather than a comedy (perhaps because thrillers are simpler---linguistically---than comedies). So, against Reverse Bayesianism, \textsc{Movies} violates the condition $\frac{\pr{\textit{Thriller}}}{\pr{\textit{Comedy}}}=\frac{\ppr{+}{\textit{Thriller}}}{\ppr{+}{\textit{Comedy}}}$. 

The counterexample also works against Awareness Rigidity. It is not true that $\pr{\textit{Thriller}}=\ppr{+}{\textit{Thriller} \vert \textit{Thriller}\vee \textit{Comedy}}$.
To see why, note that this counterexample is a case of refinement. First, you categorize movies  by just language and genre, and then you add a further category,  level of difficulty. <!---In the scenario \textsc{Friends}, instead, the possibility space grew by adding situations in which your partner and best friends met neither as lovers nor solely as friends.^[The addition of the hypothesis \textit{Surprise} is, however, an ambiguous case. For one thing, \textit{Surprise} is a novel hypothesis that cannot be subsumed under \textit{Friends/acquaintances} or \textit{Affair}. On the other, \textit{Surprise} seems a refinement of \textit{Friends/acquaintances}, since a meeting for planning a surprise is a more specific way to describe a meeting of acquaintances. We will provide a more clear-cur example of expansion later in the paper.]--->  <!---So if \textsc{Movies} is a case of refinement, ---> So the proposition which picks out the entire possibility space should be the same before and after awareness growth, for example, $\textit{Thriller}\vee \textit{Comedy}$.  In cases of awareness growth by refinement, then, Awareness Rigidity mandates that all probability assignments stay the same. But \textsc{Movies} does not satisfy this requirement.

This is all well and good, but how strong of a counterexample is this? Steele and Stefánsson consider an objection:

  > It might be argued that our examples are not illustrative of ... a simple growth in awareness; rather, our examples illustrate and should be expressed 
  formally as complex learning experiences, where first there is a growth in awareness, and then 
  there is a further learning event ... In this way, one could argue that the awareness-growth 
  aspect of the learning event always satisfies Reverse Bayesianism 
 
 \noindent 
Admittedly, \textsc{Movies} 
can be split into two episodes. In the first, you entertain a 
new variable besides language and genre, namely the language difficulty of the movie. 
In the second episode, you learn something you did not consider before, namely that the owner is simple-minded. Could Reserve Bayesianism still work for 
the first episode, but not the second? Steele and Stefánsson do not 
address to this question explicitly, but they insist that no matter the answer 
both episodes are instances of awareness growth. We agree with Steele and Stefánsson on this point. 
Awareness growth is both \textit{entertaining} a new proposition not in the initial awareness state of the agent and \textit{learning} a new proposition not in the initial awareness state. Nonetheless, we we still wonder. Is the second episode (learning something new) necessary for the counterexample to work together with the first episode (refinement without learning)? 

Suppose the counterexample did work only in tandem with an episode of learning something new. If that were so,  defenders of Reverse Bayesianism or Awareness Rigidity could still claim that their theory applies to a large class of cases. It applies to cases of awareness refinement without learning and also to cases of awareness expansion. For recall that the first putative counterexample about awareness expansion---\textsc{Friends}---did not challenge Reverse Bayesianism insofar as the latter is formulated in terms of its close cousin, Awareness Rigidity. So the force of Steele and 
Stefánsson's counterexamples would be rather limited.

Or perhaps there is a more straightforward counterexample that only depicts mere refinement without an episode of learning and that still challenges Reverse Bayesianism and Awareness Rigidity? As we shall soon see, the answer to this question is indeed positive. 


<!---
Steele and Stefansson consider the objection that 
this is not a simple case of awareness growth: 

  > It might be argued that our examples are not illustrative of a simple learning event 
  (a simple growth in awareness); rather, our examples illustrate and should be expressed 
  formally as complex learning experiences,where first there is a growth in awareness, and then 
  there is a further learning event ... In this way, one could argue that the awareness-growth 
  aspect of the learning event always satisfies Reverse Bayesianism (the new propositions 
  are in the first instance evidentially irrelevant to the comparison of the old basic propositions). 
  Subsequently, however, there may be a revision of probabilities over some partition of the possibility space
  
We think this is a reasonable objection. Steele and Stefansson dismiss it 
because---they write---'the two-part structure seems ultimately unmotivated. 
The second learning stage is an odd, spontaneous learning event that 
would be hard to rationalise.' This response might be too quick. 
--->





# A better counterexample
\label{sec:better}

Steele and Stefánsson's counterexample to Reverse Bayesianism in the case of refinement is rather complex, perhaps unnecessarily so. We now present something simpler:

>   \textsc{Lighting:} You have evidence that favors a certain hypothesis, say a witness 
saw the defendant around the crime scene. You give some weight to this evidence. 
In your assessment, that the defendant was seen around the crime scene raises 
the probability that the defendant was actually there. But now you wonder, what if it was dark when the witness saw the defendant? You become a bit more careful and settle on this: if the lighting conditions were good, you should still trust the evidence, but if they were bad, you should not. Unfortunately, you cannot learn about the actual lighting conditions, but the mere realization that it \textit{could} have been dark  makes you change the probability that the defendant was actually there, based on the same eveidence. 

<!---Suppose you do learn that the lighting conditions were bad. In that case, 
the evidence at your disposal should no longer favor the hypothesis that 
the defendant was actually around the crime scene. After your awareness has grown, the probabilty of that hypothesis has gone down.---> 

\noindent
This scenario is simpler because it consists of mere refinement. You wonder about the lighting conditions but you do not learn what they were. Still, mere refinement in this scenario challenges Reverse Bayesianism and Awareness Rigidity. That this should be so is not easy to see. Fortunately, the theory of Bayesian networks helps to see why. 

A Bayesian network is a formal model that consists  of a graph accompanied by a probability distribution. The nodes in the graph represent random variables that can take different values. We will use 'nodes'  and 'variables' interchangeably. The nodes are connected by arrows, but no loops are allowed, hence the name direct acyclic graph (DAG). In this framework, awareness growth brings about a change in the graphical network---nodes and arrows are added or erased---as well as a change in the probability distribution from the old to the new network. 

To model the scenario \textsc{Lighting} with Bayesian networks, 
we start with this graph: 
\[H \rightarrow E,\]
where $H$ is the hypothesis node and $E$ the evidence node. If an arrow goes from $H$ to $E$, the probability distribution associated with the Bayesian network should be defined by 
conditional probabilities of the form $\pr{E=e \vert H=h}$, where uppercase letters represent the variables (nodes) and lower case letters represent the values of these variables.^[A major point of contention in the interpretation of Bayesian networks is is the meaning of the directed arrows. They could be interpreted causally---as though the direction of causality proceeds from the events described by the hypothesis to event described by the evidence---but they need not be. REFERENCES?] 

Since you trust the evidence, you think that it is more likely under the hypothesis that the defendant was present at the crime scene than under the alternative hypothesis: 
\[\pr{\textit{E=seen} \vert \textit{H=present}} > \pr{\textit{E=seen} \vert \textit{H=absent}}\]
<!---It is not necessary to fix exact numerical values for these conditional probabilities.---> The inequality is a qualitative ordering of how plausible the evidence is in light of competing hypotheses. No matter the numbers, by the probability calculus, it follows that the evidence raises the probability of the hypothesis \textit{H=present}.
<!---:
\[\pr{\textit{H=present}\vert \textit{E=seen}} > \pr{\textit{H=present}}\]
\noindent
--->

Now, as you wonder about the lighting conditions,  the graph should 
be amended:
\[H \rightarrow E \leftarrow L,\]
where the node $L$ can have two values, 
\textit{L=good} and \textit{L=bad}. A plausible way to update your 
assessment of the evidence is as follows:
\[\ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{L=good}} > \ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=good}}\]
\[\ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{bad}} = \ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=bad}}\]

\noindent
Note the change in the probability function from $\pr{}$ to $\ppr{+}{}$. 
Here is what you are thinking: if the lighting conditions were good, you should still trust the evidence like you did before. But if the lighting conditions were bad, you should regard the evidence as no better than chance.  <!---Again, there are no exact numerical values here. --->

Should you now assess the evidence at your disposal---that the 
witness saw the defendant at the crime scene---any differently than you did before?
<!---Would it  be wrong to think the evidence had the same value?---> The evidence would have the same value if the likelihood ratios associated with it relative to the competing hypotheses were the same before and after awareness growth:
\[\frac{\pr{E=e \vert H=h}}{\pr{E=e \vert H=h'}}= \frac{\ppr{+}{E=e \vert H=h}}{\ppr{+}{E=e \vert H=h'}} \tag{C}.\]
But it would be quite a coincidence if (C) were true. For concreteness, let's use some numbers:
\[\pr{\textit{E=seen} \vert \textit{H=present}}=\ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{L=good}}=.8\] 
\[\pr{\textit{E=seen} \vert \textit{H=absent}}=\ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=good}}=.4\]
\[\ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{L=bad}} = \ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=bad}}=.5.\]
So the ratio $\frac{\pr{\textit{E=seen} \vert \textit{H=present}}}{\pr{\textit{E=seen} \vert \textit{H=absent}}}=2$. Before awareness growth, you thought the evidence favored the hypothesis \textit{H=present} moderately strongly.  That seemed reasonable. But, after the awareness growth, the ratio $\frac{\ppr{+}{\textit{E=seen} \vert \textit{H=present}}}{\ppr{+}{\textit{E=seen} \vert \textit{H=absent}}}=\frac{.65}{.45}\approx 1.44$.^[The calculations here rely on the dependency 
structure encoded in the Bayesian network (see starred step below).
\begin{align*}
\ppr{+}{\textit{E=seen} \vert \textit{H=present}} &= \ppr{+}{\textit{E=seen} \wedge \textit{L=good} \vert \textit{H=present}}+\ppr{+}{\textit{E=seen} \wedge \textit{L=bad} \vert \textit{H=present}}\\
&= \ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{L=good}}  \times \ppr{+}{\textit{L=good} \vert  \textit{H=present} }\\ & +\ppr{+}{\textit{E=seen}  \vert \textit{H=present} \wedge \textit{L=bad}} \times \ppr{+}{\textit{L=bad} \vert  \textit{H=present}}\\
&=^* \ppr{+}{\textit{E=seen} \vert \textit{H=present} \wedge \textit{L=good}}  \times \ppr{+}{\textit{L=good}}\\ & +\ppr{+}{\textit{E=seen}  \vert \textit{H=present} \wedge \textit{L=bad}} \times \ppr{+}{\textit{L=bad}}\\
&= .8 \times .5 +.5 *.5 = .65 
\end{align*}
\begin{align*}
\ppr{+}{\textit{E=seen} \vert \textit{H=absent}} &= \ppr{+}{\textit{E=seen} \wedge \textit{L=good} \vert \textit{H=absent}}+\ppr{+}{\textit{E=seen} \wedge \textit{L=bad} \vert \textit{H=absent}}\\
&= \ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=good}}  \times \ppr{+}{\textit{L=good} \vert  \textit{H=absent} }\\ & +\ppr{+}{\textit{E=seen}  \vert \textit{H=absent} \wedge \textit{L=bad}} \times \ppr{+}{\textit{L=bad} \vert  \textit{H=absent}}\\
&=^* \ppr{+}{\textit{E=seen} \vert \textit{H=absent} \wedge \textit{L=good}}  \times \ppr{+}{\textit{L=good}}\\ & +\ppr{+}{\textit{E=seen}  \vert \textit{H=absent} \wedge \textit{L=bad}} \times \ppr{+}{\textit{L=bad}}\\
&= .4 \times .5 +.5 *.5 = .45 
\end{align*}] This argument can be repeated with several other numerical assignments.\todo{Need a more general argument here. Simulation?}
So, quite often, mere refinement can weaken the evidence, 
even without learning anything new.^[If you did learn that the lighting conditions were bad, the evidence would become even weaker, effectively worthless:
\[\frac{\ppr{+, \textit{L=bad}}{\textit{E=seen} \vert \textit{H=present}}}{\ppr{+, \textit{L=bad}}{\textit{E=seen} \vert \textit{H=absent}}}=1,\]
where $\ppr{+, \textit{L=bad}}{}$ is the new probability function after learning that \textit{L=bad}.
]

Why does all this matter? We have seen that, after awareness growth, you should regard the evidence at your disposal as one that favors \textit{H=present}  less strongly. Since the prior probability of the hypothesis should be the same before and after awareness growth, it follows that
\[\ppr{+}{\textit{H=present} \vert \textit{E=seen}} \neq \pr{\textit{H=present} \vert \textit{E=seen}}.\]
<!--\[\ppr{+, \textit{L=bad} }{\textit{H=present} \vert \textit{E=seen}} \neq \pr{\textit{H=present} \vert \textit{E=seen}}\]--->
This outcome violates Awareness Rigidity. For recall that in cases of refinement, Awareness Rigidity requires that the probability of basic propositions stay fixed. 

Reverse Bayesianism is also violated. For example, the ratio of the probabilities of \textit{H=present} to \textit{E=seen}, before and after awareness growth, has changed:
\[\frac{\ppr{\textit{E=seen}}{\textit{H=present}}}{\ppr{ \textit{E=seen}}{\textit{H=seen}}} \neq \frac{\ppr{+, \textit{E=seen}}{\textit{H=present}}}{\ppr{+, \textit{E=seen}}{\textit{H=seen}}},\]
where $\ppr{\textit{E=seen}}{}$ and $\ppr{+, \textit{E=seen}}{}$ represent the agent's degrees of belief, before and after awareness growth, updated by the evidence $\textit{E=seen}$.



# Downstream and upstream refinement
\label{sec:downstream}


Unlike \textsc{Movies}, the counterexample \textsc{Lighting} works even though it only depicts
refinement without learning. Defenders of Reverse Bayesianism and Awareness Rigidity
can no longer claim that their theories work when awareness growth is not intertwined 
with learning. So, Steele and Stefánsson's critique of these theories 
sits now on firmer ground. And yet, the scope of this critique should not be exaggerated. As we shall now see, there are cases of refinement in which Reverse Bayesianism and Awareness Rigidity are perfectly fine in their place. 


Consider this variation of the \textsc{Lighting} scenario:

  > \textsc{Veracity}: A witness saw that the defendant was around the crime scene and you initially took this to be evidence that the witness was actually there. But then you had second thoughts. Instead of worrying about the lighting conditions, you worry that the witness might be lying or misremembering what happened. Perhaps, the witness was never there, made things up or mixed things up. 
  But despite that, you do not change anything of your initial assessment of the evidence. 
  
\noindent  
The rational thing to do here is to stick to your guns and not change your earlier assessment of the evidence. Why should that be so? And what is the difference with \textsc{Lighting}?
Once again, Bayesian networks proves to be a 
good analytic tool here. 

The graphical network should initially look 
like this:
\[H\rightarrow E\]
But, as your awareness grows, 
the graphical network should be updated:
\[H\rightarrow E \rightarrow R\]
The hypothesis node $H$ bears on the 
whereabouts of the defendant. Note the difference between $E$ and $R$. The evidence node bears on what the witness saw. The reporting node bears on what the witness reports to have seen. The chain of transmission from 'seeing' to 'reporting' may fail for various reasons, such as lying or confusion. 

It pays to highlight the difference between \textsc{Lighting} and \textsc{Veracity}. They are both cases of refinement. In one, what the witness saw could have occurred under good or bad lighting conditions; in the other, what the witness saw could have been reported truthfully or untruthfully. But refinement is structurally different in the two cases. In  \textsc{Lighting}, the connection between the evidence and the hypothesis undergoes a change, since the lighting conditions affect the witness' ability to have reliable experiences of what happened. In \textsc{Veracity}, instead, the connection between the evidence and the hypothesis is not affected. At stake is the extent to which what the witness saw, if anything, is reported truthfully or not.

So, even if \textsc{Veracity} is a case of refinement, the old and new probability functions agree with one another completely. The conditional probabilities, $\pr{E=e \vert H=h}$ should be the same as $\ppr{+}{E=e \vert H=h}$ for any values $e$ and $h$ of the variables $H$ and $E$ that are shared before and after awareness growth. Given the dependency structure of the two Bayesian networks---first, $H\rightarrow E$ and then $H\rightarrow E \rightarrow R$---the equality is easy to establish formally.^[GIVE PROOF]
Thus, Reverse Bayesianism and Awareness Rigidity are perfectly fine in
scenarios like \textsc{Veracity}.

A confusion should be eliminated at this point. We do not intend to suggest that the assessment of the probability of the hypothesis \textit{H=present} should undergo no change at all. If you worry that the witness could have lied, shouldn't this affect your degree of beliefs in the veracity of what they said about the defendant's whereabouts? Surely so. But note that in \textsc{Veracity} an episode of awareness refinement takes place together with a form of retraction. Initially, what is taken to be known, after the learning episode, is that the witness \textit{saw} the defendant around the crime scene. But after awareness growth, you realize your learning is in fact limited to what the witness \textit{reported} to have seen. So the previous learning episode is retracted and replaced by a more careful statement of what you learned. This retraction will affect the probability you assign to the hypothesis \textit{H=seen}, but this does not conflict with Reverse Bayesianism or Awareness Rigidity. In \textsc{Lighting}, instead, no retraction of the evidence takes place. The evidence that is known remains the fact that the witness saw the defendant around the crime scene, even though that experience could have been misleading due to bad lighting conditions. 


<!---These remarks suggest that  Bayesian networks helped to distinguish two cases of refinement, exemplified by \textsc{Lighting} (and in a more complicated version, \textsc{Movies}) and \textsc{Veracity}. It is only in cases like \textsc{Lighting} in which Reverse Bayesianism and Awareness Rigidity should be given up, not in cases like \textsc{Veracity}. There may actually be other paradigmatic cases of refinement in which Reverse Bayesianism does or does not hold, but limitations of space and time compel us to move on.
--->
<!---Briefly mention  mediating refinement: 
\[H\rightarrow E\]
\[H\rightarrow M \rightarrow E\]
--->

Where does this leave us? The following are now well-established: (a) Reverse Bayesianism (or its close cousin Awareness Rigidity) handles successfully cases of awareness expansion; (b) it also handles successfully cases of refinement like \textsc{Veracity}; but (c) it does fail in cases of refinement like \textsc{Lighting}. <!--- (and in the more complicated version \textsc{Movies}). ---> <!---The category 'refinement' 
which Steele and Stefánsson deploy in their analysis of awareness growth is too coarse.--->   So, ultimately, Steele and Stefánsson's critique only targets a subclass of refinement cases. The scope of this critique is therefore somewhat limited. 
And yet, we do not think the prospects for Reverse Bayesianism are good. In this respect, we tend to agree with Steele and Stefánsson. But we conjecture that there is a deeper reason why Reverse Bayesianism cannot ultimately work, besides possible counterexamples that may be leveled against it. It seeks to provide a formal, almost algorithmic solution to the problem of awareness growth, and this formal aspiration is likely to lead us down the wrong path. 

To see why, consider again the distinction between the two cases of refinement. Reverse Bayesianism is perfectly fine in scenarios like \textsc{Veracity}, but fails in scenarios like \textsc{Lighting}. What is that so? The two scenarios are structurally different, and this difference can be appreciated by looking at the Bayesian networks used to model them.  There may be other, more fine-grained distinctions to be made.
In \textsc{Veracity}, the new node is added downstream. Since the conditional probabilities associated with the upstream nodes are unaffected, Reverse Bayesianism is vindicated. By contrast, in \textsc{Lighting}, the new node is added upstream. Since the conditional probabilities that are associated with the downstream nodes will often have to change, Reverse Bayesianism fails here. 

The upshot is this. Structural---possibly causal---constraints about how we conceptualize the world seems to be the guiding principles about how we update the probability function through awareness growth, not a formal principle like Reverse Bayesianism. We further elaborate on this conjecture in the final section. 


# Material, not formal constraints
\label{sec:material}


Those who sympathize with a formal, algorithmic solution to the problem of awareness 
growth might offer the following reply. Granted, Reverse Bayesianism (or its close cousins, Awareness Rigidity) are not general enough formal constraints. They fail sometimes. But, arguably, a weaker formal constraint may be immune from counterexamples.  We now explore what this weaker formal constraint might look like for upstream refinement cases like \textsc{Lighting}. 

Recall that, in \textsc{Lighting}, the probability 
functions $\pr{}$ and $\ppr{+}{}$ 
do not assign the same weight to the evidence relative 
to the competing hypotheses, except in somewhat 
exceptional circumstances. <!---Hence, Reverse Bayesianism and Awareness Rigidity fail 
in this scenario. --->
But despite that, the two probability 
functions agree in one important respect: 
\[\pr{E=e \vert H=h} \geq \pr{E=e \vert H=h'} \textit{ iff } \ppr{+}{E=e \vert H=h} \geq \ppr{+}{E=e \vert H=h'} \tag{$C^*$},\]
where (i) $E$ and $H$ are nodes that are part of the graphical network before and after awareness growth, and (ii)  there is a direct path from $H$ to $E$ before and after awareness growth.\todo{Is the condition of direct path necessary?} In other words, the plausibility ordering between hypotheses and evidence is preserved. Condition $(C^*)$ can serve as a conservative constraint that governs the relationship between $\pr{}$ and $\ppr{+}{}$. It is satisfied in the scenario \textsc{Lighting}, but how general is this condition?

Interestingly, $(C^*)$ holds generally 
in a class of Bayesian networks, under minimal, and entirely reasonable, 
assumptions. Assume the Bayesian network has a node $E$ with an incoming arrow from node $H$, before and after awareness growth. After awareness growth, besides $E$ and $H$, another variable $Y$ is added upstream.  The new graph looks like this:
\[H\rightarrow E \leftarrow Y.\]
For simplicity, we assume that variables are binaries. 
All we need is the following assumption:
\[\pr{E=e \vert H=h} \geq \pr{E=e \vert H=h'} \]
\[\textit{ iff }\] 
\[\ppr{+}{E=e \vert H=h \wedge Y=y} \geq \ppr{+}{E=e \vert H=h' \wedge Y=y} \tag{EQUAL}\]
\[\textit{ iff }\] 
\[\ppr{+}{E=e \vert H=h \wedge Y=y'} \geq \ppr{+}{E=e \vert H=h' \wedge Y=y'}\]
This assumption says that the plausibility ordering remains the same before and after awareness growth \textit{all else being the same}. It is a minimal assumption, but enough to establish ($C^*$).^[From (EQUAL) and via this chain of equivalences:
\[[a \geq a' \& b\geq b'] \textit{ iff } [ak \geq a'k \& b(1-k)\geq b'(1-k) (\textit{with }k>0)] \textit{ iff }  [ak+b(1-k) \geq a'k+b'(1-k)],\]
it follows that
\[\pr{E=e \vert H=h} \geq \pr{E=e \vert H=h'} \]
\[\textit{ iff }\] 
\[\ppr{+}{E=e \vert H=h \wedge Y=y}\times \ppr{+}{Y=y} + \ppr{+}{E=e \vert H=h \wedge Y=y'}\times \ppr{+}{Y=y'} \]
\[\geq\]
\[\ppr{+}{E=e \vert H=h' \wedge Y=y}\times \ppr{+}{Y=y} + \ppr{+}{E=e \vert H=h' \wedge Y=y'}\times \ppr{+}{Y=y'} \]
We are done since, by the law of total probability and the probabilistic 
dependencies in the graph, ($C^*$) 
is equivalent to the above statement.]


The formal requirement (EQUAL) seems quite general. It should also hold in Steele and 
Stefánsson's scenario \textsc{Movies}, another case 
of upstream refinement.^[We  briefly explain why. At first, the graphical network looks like this:
\[\textit{Genre} \rightarrow \textit{Enjoyment} \leftarrow \textit{Language},\]
where each node can take two values: \textit{Genre=comedy} and \textit{Genre=thriller};
\textit{Language=french} and \textit{Language=german}; and \textit{Enjoyment=yes} and   \textit{Enjoyment=no}. <!---Assume you have no reason to think the language or genre or the movie is one of the two. But also ---> Assume you are ranking the options in terms of how they are going to contribute to your enjoyment (\textit{Enjoyment=yes}).
<!---as follows:
\[\textit{Language=french} \wedge \textit{Genre=comedy}\]
\[\textit{Language=german} \wedge  \textit{Genre=thriller}\]
\[\textit{Language=french} \wedge \textit{Genre=thriller}\]
\[\textit{Language=german} \wedge  \textit{Genre=comedy}\]
--->
<!---You are more likely to enjoy a comedy in French than anything else, but you are more likely to enjoy a thriller in German than one in French, and your lowest preference is for a comedy in German.---> This ranking can be encoded by conditional probability statements of the form 
\[\pr{\textit{Enjoyment=x} \vert \textit{Language=y} \wedge \textit{Genre=z}} \geq \pr{\textit{Enjoyment=x} \vert \textit{Language=y'} \wedge \textit{Genre=z'}}.\]
The first episode of awareness growth in \textsc{Movies} consists in realizing 
that the linguistic difficulty of the movie could also be a factor. 
So the expanded graphical network now becomes:
\begin{align*}
\textit{Difficulty} &\\
\downarrow \\
\textit{Genre} \rightarrow \textit{Enjoyment} &\leftarrow \textit{Language}\\
\end{align*}
\noindent
<!---The new node can take two values: \textit{Difficulty=high} and \textit{Difficulty=low}.--->
Your ranking of what is likely to give you enjoyment should now be updated and made more specific, but much of the earlier ordering can be retained, that is:
\[\pr{\textit{Enjoyment=x} \vert \textit{Language=y} \wedge \textit{Genre=z}} \geq \pr{\textit{Enjoyment=x} \vert \textit{Language=y'} \wedge \textit{Genre=z'}}\] \[\textit{ iff }\] \[\ppr{+}{\textit{Enjoyment=x} \vert \textit{Language=y} \wedge \textit{Genre=z}} \geq \ppr{+}{\textit{Enjoyment=x} \vert \textit{Language=y'} \wedge \textit{Genre=z'}}.\]
The difference with condition ($C^*$) is that here two propositions, not just one, are conditioned on. So ($C^*$) should be be generalized, accordingly, but the general idea remains the same.]
So the algorithmic solution to the problem of awareness growth might go like this: for expansion and downstream refinement, uses Awareness Rigidity, and for downstream refinement, use the weaker (C*).

But this solution cannot ultimately work. There will be cases in which the plausibility ordering is not preserved because (EQUAL) does not hold. For suppose you have evidence that---in your judgment---reliably tracks a hypothesis, say you think that appearance as of hands reliably tracks the presence of hands:
\[\pr{E=\textit{as-of-hands} \vert H=\textit{hands}} > \pr{E=\textit{as-of-hands} \vert H=\textit{no-hands}} \]
You now entertain a 'switching hypothesis': when you see a hand, there is no hand, and when you do not see a hand, there is a hand. In this case, (EQUAL) would be violated since
\[\ppr{+}{E=\textit{as-of-hands} \vert H=\textit{hands} \wedge Y=\textit{switching}} < \ppr{+}{E=\textit{as-of-hands} \vert H=\textit{no-hands} \wedge Y=\textit{switching}}\]
<!---In more common skeptical scenarios without a switching hypothesis, however, (EQUAL) should still hold. For what skeptical scenarios often do is to neutralize the value of the evidence, not so much switching its value. ---> 
This scenario is far-fetched---does the switching hypothesis even make sense?---but suggests that no matter how weak a formal constraint might be, there is likely a counterexample. 


<!---^[A generalzied version iof ($C^*) wouldbe as follows. $Let $E$ be a node with several incoming arrows departing from a finite set of nodes, $X_1, X_2, \dots X_k$ that are shared before and after awareness growth. Then:
\[\pr{E=x \vert X_1=x_1 \wedge X_2=x_2 \dots X_k=x_k} \geq \pr{E=x \vert X_1=x_1' \wedge X_2=x_2' \dots X_k=x_k'}\] 
\[\textit{ iff }\] 
\[\ppr{+}{E=x \vert X_1=x_1 \wedge X_2=x_2 \dots X_k=x_k} \geq \ppr{+}{E=x \vert X_1=x_1' \wedge X_2=x_2' \dots X_k=x_k'}.\]
]] 
--->









# Conclusion

We argued that Steele and Stefánsson's case against Reverse Bayesianism is weaker than it might seem at first. The scenario \textsc{Movies}---which is their key counterexample---is unconvincing since it mixes learning and refinement. To avoid this, we constructed a more clear-cut case of refinement, \textsc{Lighting}, in which both Awareness Rigidity and Reverse Bayesianism fail unequivocally. At the same time, we showed that there are cases of downstream refinement like \textsc{Veracity}
in which Reverse Bayesianism and Awareness Rigidity are perfectly fine in their place. In cases of upstream refinement, like \textsc{Lighting}, one can be tempted to formulate a weaker formal constraint that would still vindicate the formalistic aspiration of Reverse Bayesianism. But no matter the constraint, there are likely to be counterexamples to it. 


<!---So the distinction between refinement and  expansion 
that Steele and Stefánsson draw, albeit a good first approximation, 
is too coarse and needs to be made more precise.--->

We conclude with a few programmatic observations. We think that the awareness of agents grows while holding fixed certain material structural assumptions, based on commonsense, semantic stipulations or causal dependency. To model awareness growth, we need a formalism that can express these material structural assumptions. This can done using Bayesian networks, and we offered some illustrations of this strategy, for example, by distinguish two forms of refinement on the basis of different structural assumptions. These material assumptions also guide us in formulating the adequate conservative constraints, and these will inevitably vary on a case-by-case basis.  Our approach stands in stark contrast with much of the literature on awareness growth from a Bayesian perspective. This literature is primarily concerned with a formal, almost algorithmic solution to the problem. We suspect that seeking such formal solution is doomed to fail. Insofar as Reverse Bayesianism is an expression of this formalistic aspiration, we agree with Steele and Stefánsson that we are better off looking elsewhere.


# Extra Materials -- IGNORE


## Expansion


There remains to examine cases of awareness expansion. They consist in the addition of another proposition not previously in the algebra,  but that is 
not a refinement of existing propositions. The addition of the hypothesis \textit{Surprise} is, however, an ambiguous case. For one thing, \textit{Surprise} is a novel hypothesis that cannot be subsumed under \textit{Friends/acquaintances} or \textit{Affair}. On the other, \textit{Surprise} seems a refinement of 
\textit{Friends/acquaintances}, since a meeting for planning a surprise is a more specific way to describe a meeting of acquaintances. A more clear-cut case of awareness expansion would be the following. The police is investigating a murder  case. There are two suspects under investigation: Joe and Sue. They both have a motive. The incriminating evidence favors one over the other, but not overwhelmingly. <!--The evidence consists in a DNA match and information about how the crime was committed.  Sue genetically matches the traces, but  is quite short and the perpetrator is known to be a  tall person. Joe is neither tall nor does he genetically match the crime traces. In light of the evidence, Sue seems more likely the culprit than Joe, but matters are still open ended. --->T hen, a new hypothesis is considered: Ela could be the perpetrator. <!--As it turns out, Ela genetically matches the traces, is tall enough to have committed the crime, and does have a motive. This seems a straightforward case of expansion because Ela, Sue and Joe are incompatible hypotheses, while  \textit{Friends/acquaintances} and  \textit{Surprise} need not be. --->
The evidence incriminates Ela almost without any doubt. Any theory of awareness growth should be able to model the difference between the example provided by Steele and Stefánsson and the criminal case just outlined. They are both, arguably, cases of expansion, but they are also different.  

Steele and Stefánsson provide a formal definition of the difference between refinement and expansion. Our observations here are largely confined at the intuitively level. Our point is that there are a number of intuitively plausible differences that a formal theory should be able to capture. The coarse distinction between refinement and expansion might be, in the end, too coarse. Relying on Bayesian networks, we will illustrate this point more precisely in the next section. 



## Steele and Stefánsson example


Before awareness growth, the Bayesian network has a simple form: \[H \rightarrow E,\] where the hypothesis variable $H$ takes two values, $H=\textit{Affair}$ and $H=\textit{Friends/acquaintances}$.  The evidence variable $E$ can take several values, one of them being $E=\textit{Secretive}$. You could have seen other things other than what you saw, but there is no need to specify the other values exhaustively. Suppose the prior odds ratio of the hypotheses is 1:1, say, because you suspected your partner might be cheating on you, and the likelihood ratio \[\frac{\pr{E=\textit{Secretive}\vert H=\textit{Affair}}}{\pr{E=\textit{Secretive}\vert H=\textit{Friends/acquaintances}}}\] is 9:1, because the
hypothesis \textit{Affair} is a better explanation of the evidence than the hypothesis \textit{Friends/acquaintances}. Then, the posterior probability given the evidence \[\pr{H=\textit{Affair} \vert E=\textit{Secretive}}\] is quite high, $\frac{9}{10}=.9$.
So $\ppr{E=\textit{Secretive}}{H=\textit{Affair}}=.9$.^[This calculation presupposes that the two hypotheses 
\textit{Affair} and \textit{Friends/acquaintances} are exclusive and exhaustive. This assumption is justified given the initial awareness state of the agent.]

After awareness growth, the Bayesian network should be modified as follows:
 \[H \leftarrow H' \rightarrow E,\]
where the new hypothesis node now consists of three values instead of two: 

$H'=\textit{Affair}$ 

$H'=\textit{Friends/acquaintances}\wedge \neg \textit{Surprise}$  

$H'=\textit{Friends/acquaintances}\wedge\textit{Surprise}$. 

\noindent
The scenario $\textit{Friends/acquaintances}$ is split into the scenario in which your partner and best friend met simply as friends or acquaintances, and the scenario in which they met to prepare a surprise party for you. On this interpretation, the counterexample by Steele and Stefánsson is a case of refinement, not expansion. We will return to this point later.

The network contains a directed arrow between the old hypothesis node $H$ and the new hypothesis node $H'$ 
This arrow can be interpreted as a bridge between the old awareness state limited to two hypotheses and the new awareness state that contains an additional hypothesis. This bridge is purely conceptual and can be defined by two sets of constrains. The first set of constrains posits that \textit{Affair} under $H$ has the same meaning as \textit{Affair} under $H'$:

$\ppr{+}{H=\textit{Affair} \vert H'=\textit{Affair}}=1$

$\ppr{+}{H=\textit{Affair} \vert H'=\textit{\textit{Friends/acquaintances}}}=0$

$\ppr{+}{H=\textit{Affair} \vert H'=\textit{Surprise}}=0$

The second set of constrains posits that hypothesis $\textit{Friends/acquaintances}$ under $H$ can be actually be interpreted in two ways under $H'$, as  $\textit{Friends/acquaintances} \wedge \neg \textit{Surprise}$ and  $\textit{Friends/acquaintances} \wedge \textit{Surprise}$. So, in other words, the episode of awareness growth consists in the realization that $\textit{Friends/acquaintances}$ can be made precise in two more specific ways:

$\ppr{+}{H=\textit{Friends/acquaintances} \vert H'=\textit{Affair}}=0$

$\ppr{+}{H=\textit{Friends/acquaintances} \vert H'=\textit{Friends/acquaintances} \wedge \neg \textit{Surprise}}=1$

$\ppr{+}{H=\textit{Friends/acquaintances} \vert H'=\textit{Friends/acquaintances} \wedge \textit{Surprise}}=0$

This bridge between $H$ and $H'$ justifies the following conservativity constraint:

\[\frac{\pr{E=\textit{Secretive}\vert H=\textit{Affair}}}{\pr{E=\textit{Secretive}\vert H=\textit{Friends/acquaintances}}} = \frac{\ppr{+}{E=\textit{Secretive}\vert H=\textit{Affair}}}{\ppr{+}{E=\textit{Secretive}\vert H=\textit{Friends/acquaintances}}}=\frac{9}{1} \] 






## Expansion: criminal case example































































