---
title: "Gaps in the Evidence"
author: "Marcello Di Bello and Rafal Urbaniak"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - Rafal_latex7.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 10pt
documentclass: scrartcl
urlcolor: blue
bibliography: [../references/referencesMRbook.bib]
csl: [../references/apa-6th-edition.csl]
indent: true
---




<!-- \tableofcontents -->


# Structure of paper

First talk about some paradigmatic legal cases and established legal framework to handle cases of missing evidence. 

One: Salem trials. Here the content of the missing is know, so is it really a case of missing evidence? 

Two: Target case. Here tha there is missing evidence is clear (vida was erased), but te question of the conten of the video is open. 

Three: could there be other cases in which whether the evidence is missing or not might depend on what kind of partisan story one subscribes to? Or perhaps there might be conflicting stories about why the evidence is missing.

Note that the legal framework only addresses cases of manifest missing evidence --- cases in which (a) we know evidence is missing and (b) we know why it is missing (e.g. bad faith, negligence, etc.), so we need to decide what to do with the information (a) and (b), (e.g. draw an adverse inference).

Two limitations of the legal framework: (1) if there is no bad faith intent, then there is no adverse inference to be drawn; (2) given a settled story about what happened, the story itself tells us some evidence is missing. But could there other cases of missing evidence---say more conjectural?

Beyond (1). Consider the case there is no bad faith intent, but the evidence is still missing. What kind of remedy could address the gap in this case? Humer's argument is that since the missing evidence could point in both directions---guilt and innocence---the evidential value should be dismissed. Missing evidence averages out and thus return the same probability of guilt as the original evidence. This argument does not seem correct. So challenge it.

Beyond (2). The even more difficult question is what to do when there is story that clearly tells us that the evidence is missing, or it is not clear that the evidence is missing. 
Here is the difference between the express "gaps" and "missing evidence" start to matter. 
For example, do you have a gap in the evidence if you have not considered evidence about how reliable an eyewitness is? Yes and no. This aspects suggests that evidence is open-ended and thus the problem gaps is less pressing.


## Key claims

(0) Start with Target case which seems to contain a lot of complexity and overview of main topics, then examine legal approach. 

(1) Difference between gaps in a clearly defined story and generic gaps in the evidence.
The former, when filled, would clearly make the decision making more accurate, while the latter could make it less accurate. So we need not obsess about gaps in general, but only gaps that are clearly articulated. Sp, a decision procedure with more evidence (filling clear gaps) is more accurate, but a decision procedure worth more evidence (not filling clear gaps) need not be more accurate. So conjectural gaps might be less important thazn clear narrative gaps.

(2) Consider now only clearly specified gaps that are accuracy enhancing. 
Such gaps in evidence may be random/fortuitous or follow a systematic pattern.
They only worrisome if they follow a systematic pattern. If they are random, they will reduce accuracy (because of 1), but not favor one side or the other systemically. So sucvh cases might not need any regulatations.

(3) Two rationales for remedies: epistemic individual specific and policy rationale. First, if evidence was intentionally removed, it is likely it would favopr the other party, etc. here an inference about what the missing/removed evidence was likely is made. No appeal to policy. Instead, we can also device a policy that says: sanction behavior that destroyed evidence when it is in bad faith. The two approaches might converge byt might also diverge sometimes. Example: evidence destruction was by accident, but there was duty for the defendant to preserve evidence. So, epistemic individual approach would not draw any adverse inference, but the policy approach would.

(4) Consider cases of missing stats about reliability of lab genetic testing
or information about visibility conditions for eyewitness. Is this a clearly defined gap in the evidence or a generic gap? 





























# Introduction

This much is uncontroversial about trial decision-making: disputes about matters of fact should be adjudicated in light of the evidence presented by the litigants.  When the answer to a question of fact is disputed, the litigants are expected to present evidence that supports their version of the facts. Whoever presents evidence strong enough 
to meet their burden of proof should prevail. 

A stylized example can make this point vivid. In a civil trial, the plaintiff sues a shop owner because of an injury that occurred in the shop. The floor was slippery. The plaintiff  tripped and fell. They had a concussion whose symptoms lasted for more than a month. They seek compensation for damages. This is the plaintiff's version of the facts. The defendant, the shop owner, responds that the floor was not slippery. The defendant did fall and had a concussion---that much is undisputed---but not because of the slippery floor. Plaintiff and defendant are disagreeing about a question of fact. What did cause the plaintiff to trip and fall? What happen, exactly, when the plaintiff tripped and fell? Evidence must be presented by the litigants to resolve the dispute. And since this is a civil trial, the decision rule, at least in some countries such as the United States, is that the party able to offer the stronger evidence prevails. If the evidence is in equipoise, the defendant prevails. In other countries, the decision rule may be different, for example, the party bringing forth the the accusation---the plaintiff---prevails provided the decision-maker is convinced by the evidence presented that the plaintiff's story is true. 

Despite differences in details about the decision rule, the need to weigh evidence
before reaching a decision should be uncontroversial. But there is a complication. Suppose the shop had cameras inside. When the plaintiff tripped and fell, the camera recorded what happened. The recording, if accessible, could unequivocally tell what happened. Suppose this is a settled fact. However, for some reason, the camera recording of that specific incident had gone missing.  There isn't much other evidence that could be gathered, except conflicting testimonies by the plaintiff and defendant. That day at that time no one else was in the shop. So, based on the available evidence, the plaintiff would have a weak case. The available evidence that supports the plaintiff's case is not any stronger than the evidence that supports the defendant's case. Merely based on the evidence  presented, the plaintiff should lose the lawsuit. 

But this outcome would be, in some important way, unsatisfactory. Why was the recording missing? The shop owner might have deleted it. Perhpas they knew they would get in trouble should the customer sue them. If so, should the case be resolved in favor of the plaintiff even though the available evidence does not tip in their favor? Perhaps so. Things might change if it turned out that---by accident---the recording was deleted. Without settling how the case should be decided right now, the upshot of this discussion is clear. 
For one thing, the evidence presented by the parties should guide trial decisions about matters of fact; there is no doubt about that. But, in some circumstances, the fact that some evidence was \textit{not} presented should also guide the decision. To examine more closely what these circumstances might be---and their significance for trial decisions---is the task of this paper. We call this the problem of gaps in the evidence or the problem of missing evidence. 

Legal systems of adjudication contain rules for handling gaps in the evidence. These rules are elaborate, subtle, intricate. We are not cataloging these rules, nor offering a comparative study of how different systems of adjudication address the problem of gaps. Our aim here is modest---that is, to map out the conceptual terrain. We will examine a few paradigmatic examples of gaps in the evidence. We will then sketch guidelines for building a taxonomy of gaps. Finally, we will discuss how epistemic and non-epistemic considerations can guide the identification of gaps in the evidence as well as how decision-makers should respond to them.


# Theoretical framework

<!---
(1) Missing evidence in general and when it happens at random need not hamper accuracy or dispute resolution. 

(2) Two assumptions: (a) missing evidence happens at random (no patterned advantage) and (b) it could be of higher or lower quality compared to existing body of evidence.

(3) Legal system cares about cases of missing evidence that are neither (a) nor (b). That is, it cares about cases in which missing evidence does not happen at random and cares about cases in which missing evidence would have clearly enhanced accuracy. 
--->

## Incompleteness and fallibility 

Imagine a system of adjudication that is immune from the problem of gaps in the evidence. The system is both complete and infallible. It has access to evidence about every possible fact at any time in any place and this evidence is infallible. The problem of gaps does not arise here. But it is not the infallibility of the system that eliminates the problem. For a fallible legal system could still avoid the problem of gaps. Think of a complete yet fallible system. It has access to evidence about every possible fact at any time in any place. Yet the evidence could be erroneous. Say, every action by any individual at any time in any place is recorded, and the recording is accessible by the legal system. This is completeness. But suppose recordings can be erroneous, say because the pixels can get messed up and depict people doing what they were not doing. This is fallibility: evidence may give a picture of the facts that does not correspond to them.  This complete yet fallible legal system would not incur the problem of gaps, but would still incur the problem of erroneous decisions. It would still be necessary in this legal system to assess the strength of evidence. Recordings that show indication of error should count as weaker evidence in favor of what they depict compared to recordings that did not show any indication of error. So the problem of gaps is not due to fallibility, but incompleteness.

In the world we live in, any system of adjudication will be fallible (relying on fallible evidence) and incomplete (without access to evidence about anyone at any time in any place). Fallibility and incompleteness are intertwined: one affects the other. Say the truth of some complex proposition $A \wedge B \wedge C$ is under dispute. There is infallible evidence that $A$ holds and infallible evidence that $C$ holds, but no infallible evidence about $C$. Suppose that $A, B$  and $C$ form a temporally ordered series of events: $A$ stands for forming an intention to do $\varphi$; $B$ stands for doing $\varphi$; and $C$ stands for bringing about a consequence of doing $\varphi$. Since $A$ and $C$ are known for sure, then $B$ becomes more likely in light of $A$ and $C$. In fact, $A$ and $C$ are fallible evidence for $B$. So, in this case, the incompleteness of the evidence about $A, B$ and $C$ implies the fallibility of the evidence about $B$.  

In light of this, one might wonder whether an infallible yet incomplete system of adjudication is conceptually possible. If incompleteness implies fallibility, then infallibility will imply completeness. But consider this set-up: every proposition in the set $\Sigma$ is causally independent of any proposition ion the set $\Delta$. Suppose a system of adjudication has access to infallible evidence about all the facts described by the propositions in $\Sigma$, but no evidence whatsoever about the facts described by the propositions in $\Delta$. This system would be infallible (all the evidence that there is infallible), yet incomplete (not every fact is evidenced by an item of evidence). There would be no fallible evidence. 

But, at any rate, why does a system of adjudication fail to be complete---that is, fail to have access to evidence about anyone in any place at any time? There could be several explanations for this failure. First, some facts may not be evidentiable, so to speak. For example, before genetic testing was invented, the fact that a blood stain carried a genetic profile  was not evidentiable; it could not be translated into evidence. Second, a fact may be evidentiable, but it was not the target of evidence. For example, a blood stain was not analyzed or no witness could see what happened inside the store when the customer tripped and fell. A pressing problem with making an evidentiable fact an actual target of evidence is that it might be too expensive or time-consuming. Third, even if a fact is evidentiable and was the target of evidence at some point, the resulting evidence could not be retained, was destroyed or deteriorated significantly later on.  Say a video recording of what happened inside the store existed, but it was later deleted. Perhaps it was too costly to keep it in storage. 

Failure to make a fact a target of evidence, as well as destruction or deterioration of the evidence could occur as mere accidents or could be done intentionally---for example, when one of the litigants in a trial had an interest in destroying the evidence. There are of course variations in between these two extremes: nor was it accidental, nor was it intentional but the destruction was due to someone's negligence or failure to follow certain standards. The destruction may also be mandated by company's standards to minimize costs or by competing interests, such as privacy.

## Gaps and accuracy

Why we should care about gaps in the evidence. If there are gaps in the evidence, what is the problem with them? Assume that the primary goal of the legal system of adjudication is making judgments about people's actions that are factually correct, that is, maximizing true positives (say, convict factually guilty people) and true negatives (say, acquit factually innocent people).^[We consider the goal of dispute resolution in footnote \ref{footnote:dispute-resolution}.] Given this assumption, does the existence of gaps in the evidence make the legal system less likely to reach accurate judgments? 

In a sense, the answer to this question is obviously positive. Because not every fact is reflected in evidence accessible to the legal system, there will be  criminal acts, frauds, infringements of rights etc. that go undetected. In fact, most crimes go undetected, and some have particularly low rates of prosecution. This is unsurprising, but a matter that pertains more squarely to institutions outside the system of adjudication itself, such as police investigation. 

Consider now a narrower question. If a defendant stands accused in a civil or criminal trial, does the fact that the evidence could be incomplete make it more likely that an erroneous judgment would be reached, either a false positive or false negative verdict? 
The answer, once again, seems positive, but a closer scrutiny shows that the matter is far from straightforward. 

Suppose that favorable and unfavorable evidence to one of the parties is always missing 
for fortuitous reasons---accidents---as well as 
occasional bad faith acts of destruction of the evidence. When this happens, there is no reason to think that trial decisions would be more prone to be erroneous. This situation is similar to when random errors, with no systemic pattern, occurs in large data collection (more on this later). Now, in individual cases, gaps in the evidence may cause errors. If exculpatory evidence ends up missing and the defendant was actually innocent, an incorrect  guilty verdict could have been avoided  had the exculpatory evidence not gone missing.  Conversely, if incriminating evidence ends up missing and the defendant was actually guilty, an incorrect acquittal could have been avoided had the incriminating evidence not gone missing. So gaps may cause mistaken verdicts in individual cases. However, we should consider the long-term accuracy of the adjudication system. Additional evidence, be incriminating or exculpatory, could  turn a would-be-correct-verdict into an incorrect one. So gaps in the evidence need not be detrimental to accuracy if they follow a random pattern. In fact, gaps in the evidence may actually be accuracy-enhancing. 

This claim can be illustrated with a simple model. First, consider the following fallible and incomplete system of adjudication. Against each trial defendants a body of (sometimes gappy) evidence is amassed. Relying on the (sometimes incomplete) evidence available, the long-run false positive rate (false conviction rate) is 30\% and the false negative rate (false acquittal rate) also 30\%. In other words, this legal system of adjudication---with occasional gaps in the evidence---has true positive and true negative rates of 70\%.   In addition, the evidence presented against defendants fails to be complete in 40\% of the cases *at random*. There is no discernible systemic pattern by which evidence goes missing. <!---This randomness assumption is important, and we will return to it later more extensively.---> 
(The numbers are illustrative and play no specific role in the argument that follows.)

Compare this fallible and incomplete system with one that is fallible but complete. In those 40\% of cases in which completeness would fail, this second system can supply complete evidence instead. Suppose the presence of complete evidence makes a difference for trial decisions in only half of those 40\% cases. So the two systems have the same 30\% rate of false positives and false negatives in 80\% of the cases. The difference is localized in 20\% of cases in which the added evidence that fills the gaps makes a difference to the decision. In those cases, the trial decision depends entirely on the added evidence that fills the gaps. So the error rates of the decisions in those cases boil down essentially to the reliability of the added evidence---that is, how well the added evidence tracks facts about guilt and innocence, specifically, how likely is it that the evidence is incriminating when the defendant is factually guilty (true positive rate) and how likely it is that it is exculpatory  when the defendant is factually innocent (true negative rate).  Now, three sub-cases must be distinguished. First, if the reliability of the added evidence is lower than that of the body of evidence without the added  evidence, the complete system will have higher error rates. Second, if the reliability of the added evidence is the same as that of the body of evidence without the added  evidence, the complete and incomplete systems will have the same error rates. Finally, if the reliability of the added evidence is greater than that of the body of evidence without the added  evidence, the complete system will have lower error rates. So, adding missing evidence to fill gaps need not improve the accuracy of trial decisions, and it may actually diminish it in some circumstances.



<!---Crucially, what is random is the unavailability of the evidence, not whether the missingf evidence is exculpatory or incriminating. Suppose that the evidence tracks the facts of guilt and innocence, as follows: 60\% of guilty defendant will face this additional evidence as incriminating and 60\% of innocent defendants will face this evidence as exculpatory. So the additional evidence has a true positive and true negative rates of 60\%.

Compare a fallible and complete system of adjudication with a fallible and incomplete one. In the latter system, assume evidence presented against defendants fails to be complete in 40\% of the cases at random, but it only matters in 20\% of cases---that is, it would have made a difference for the decision in 20\% of the cases. So, in those 20% of cases in which the missing evidence would have been decisive, either conforms what the smaller body of evidence would have said or turns things around. so in 20\% of the cases the system's reliability is the same as the missing evidence reliability.

Compare this system with another system that relies on more complete evidence.
Suppose the additional evidence materializes and is accessible at random, say it is accessible in 20% of the cases. 
Assume this evidence makes a different to the decision, in 20\% of the case in which this evidence materializes the decision depends on that additional evidence only. So, while 80\% of defendants will be judged  with a false positive and false negative rates of 30\%, the other 20% will be judged with rates of error of 40\%. So overall the error rates of the system with additional evidence would be worse. If the additional evidence had a true positive and true negative rates of 70\%, its addition would make no difference to the long-term accuracy of the system.

--->

<!---

NEED TO CHANGE AND REFINE THAT EXAMPLE BELOW: (I) ASSUME MISSING EVIDENCE OCCURS IN 40\% OF CASES AT RANDOM, BUT IT ONLY MATTERS IN 20\% OF CASES--MAKES A DIFFERENCE FOR DECISION IN 20\% OF CASES. IN THOSE 20% OF CASES THAT MISSING EVIDENCE ITSEL IS DECISIVE, EITHER CONFORMS WHAT THE SMALLER BODY OF EVIDENCE WOULD HAVE SAID OR TURNS THINGS AROUND. SO IN 20\% OF THE CASES THE SYSTEM'S RELIABILITY IS THE SAME AS THE MISSING EVIDENCE RELIABILITY.
(II) THREE CASES HERE: (II-A) ONE, IF THE MISSING EVIDENCE RELIABILITY IS LOWER THAN THE THE BODY OF EVIDENCE (WITHOUT THE ADDED MISSING EVIDENCE), THEN WE HAVE A REDUCTION OF RELIABILITY OF THE DECISION SYSTEM. (II-B) SECOND, IF THE MISSING EVIDENCE HAS THE SAME RELIABILITY, WE HAVE NO CHANGE. T(III-C) HIRD, IF IT IS BETTER, THEN WE HAVE AN IMPROVEMENT. NEITHER OF THESE THREE CASES IS NECESSARY, SO WE DO NOT KNOW WHETHER ADING THE MISSING EVIDENCXE IMPROVES ACCURACY OF TRIAL DECISION MAKING. TO ENSURE THAT ADDING MISSING EVIDENCE IMPROVES ACCURACY WE NEED TO ENSURE THAT WE ARE IN (III-C) ONLY. 
--->

We now have an answer to our question: how do gaps in the evidence impact accuracy?
Whenever the addition of the missing evidence would have improved the reliability of the available evidence,  gaps in the evidence are regrettable, because they lower the error rates of the decision system. However, whenever a body of evidence with gaps is not any worse in terms of reliability than a complete body of evidence, gaps in the evidence are not regrettable. If a body of evidence with gaps is better in terms of reliability than a complete body of evidence, gaps in the evidence are actually preferable.^[Besides accuracy, another important goal of trial adjudication is the timely resolution of disputes. We take no position whether on objection should take priority over the other.  But, interesting, gaps in the evidence have the same double-sided impact on accuracy and dispute resolution. Gaps may enhance or diminish accuracy, and similarly, they may favor or hinder dispute resolution. A complete body of evidence may seem more prone to lead to dispute resolution, in the sense that it can close off questions and doubts that an incomplete body of evidence would instead leave open. In this sense, complete evidence seems conducive to dispute resolution. On the other hand, the signal-to-noise ratio---or what we earlier called the reliability of the evidence---in a complete body of evidence could be lower than in an body of evidence with gaps. When this occurs, the complete body of evidence would be less likely to settle a dispute and may actually invite further litigation. \label{footnote:dispute-resolution}] We will look at a examples of when a complete body of evidence may be less reliable than an incomplete one later on. Crucially, this answer to the question about the impact of gaps on accuracy is premised on the assumption that gaps arise for fortuitous and random processes; they do not follow a systemic pattern. When they do follow a systemic pattern, gaps in the evidence pose an additional problem. We now turn to this additional problem.


## Random or systemic gaps 

To underscore the point about random patterns in evidence gaps, it is instructive to draw a comparison with data collection. The problem of gaps in the evidence is pervasive and not confined to legal systems of adjudication. For example, researchers in the social sciences may need to make inferences from data sets that contain gaps:

 > consider a large
 survey of families conducted in 1967 with many socioeconomic variables recorded, and a
 follow-up survey of the same families in 1970. Not only is it likely that there will be a few
 missing values scattered throughout the data set, but also it is likely that there will be a large
 block of missing values in the 1970 data because many families studied in 1967 could not be
 located in 1970. (Inference and Missing Data
Author(s): Donald B. Rubin Source: Biometrika, Vol. 63, No. 3 (Dec., 1976), pp. 581-592)
 
In such cases, it is paramount to understand the mechanism that explains why some data points can go missing. If randomness is the cause, that some data are missing should raise a minor problem. In the quotation above, the researcher was attempting to paint an accurate picture of large scale historical trends in socioeconomic variables for families in the 60's and 70's. That individual data points are missing at random should not affect the understanding of these large scale historical trends.  If, instead, the mechanism  exhibits a systemic pattern, that pattern must be taken into account and the inferences drawn from the data should be corrected. What this correction should be is a difficult question to answer. 

The problem of gaps in the evidence in legal systems of adjudication shares some of the problem of gaps in data, but is also distinctive. It is distinctive in that the causes for why evidence goes missing in legal trial are not the same as the causes why data can go missing. On the other hand, there is an important parallelism. Data points  can be missing because of random error in observational data. Similarly, legal evidence can be missing because of fortuitous circumstances that do not follow any systemic pattern.  

<!---So filling gaps in the evidence need not improve accuracy in the long-run. This holds in the simple example above, and there may be variations that invalidate this conclusion. The key assumption in the example is that the additional evidence materialized and was accessible to system at random. By contrast,
--->

What happens when gaps in the evidence do follow systemic pattern? The problem of gaps seems more acute when one side or the other has better access to complete evidence---say for economic reasons---and then takes advantage of what we might term \textit{informational asymmetry}. In this sense, symmetric (random) gaps in the evidence are  less worrisome---if at all---than asymmetric (systemic) gaps in the evidence. When gaps in the evidence follow a systemic pattern, they do have an additional detrimental effect on accuracy as well as fairness. For suppose wealthy defendants have better access to additional evidence and would use that evidence whenever it would benefit their case. This would cause a unilateral reduction of findings of liability against wealthy defendants. So, a tentative conclusion here is that gaps in the evidence are particularly worrisome when they are asymmetric, and less so when they occur for fortuitous circumstances even when they might have a negative effect on accuracy.


## Guiding questions

In light of the above discussion, the final question to ask concerns how the legal system should respond to gaps in the evidence, what rules (if any) it should put in place to remedy gaps. We have seen that gaps in the evidence are not necessarily a bad thing. It is not true, in general, that gaps in the evidence increase the likelihood that a legal decision could be erroneous. <!---Now, when rules are put in place to remedy these gaps, they may serve different purposes, but it would odd that their purpose would be simply to avoid gaps for the sake of avoiding gaps. --->
With this in mind, the following critical questions can guide decisions 
on how to respond to gaps in the evidence:

\begin{itemize}

\item[(Q1)] Compare the body of available evidence (with gaps) and the would-be body of evidence (without gaps). Do we have reasons to believe that the complete body would be more reliable than than the body of available evidence? 

\item[(Q2)] What is the cause that brought about the gaps in the evidence? Is it a fortuitous fact or the result of a systemic pattern that advantages one or the other party in the trial? 

\end{itemize}



These two critical questions help to outline a general framework to design remedies for missing evidence. Consider the first question. If the answer is no, the missing evidence should raise no concern. It has no discernible impact on accuracy. Answering this first question might be quite difficult, though. For how we make an assessment of what the would-be complete evidence looks like if the missing evidence is not actually present? In the next section, we will see that this question can be realistically answered in some cases. In fact, whether such a question can be realistically answered is itself a good criterion for making decisions about missing evidence. 

 If the answer to the first questions is yes, the missing evidence will have an impact on accuracy. Then, consider the second critical question.  If the missing evidence is the result of a systemic pattern, this would make the evidence particularly problematic. Insofar as this pattern can be corrected and eliminated---by means of appropriate incentives---suitable remedies for missing evidence should be formulated. These remedies should aim to compensate the party that is negatively affected by the missing evidence. But if the missing evidence is the result of a fortuitous fact---good or bad lack, depending on which side we look---there cannot much the legal system can do. The reduced level of accuracy that results from the missing evidence might be an inevitable cost that any system of adjudication must bear.

These remarks are general, but are not uninformative. They draw a line between gaps in the evidence the system of adjudication should care about, and gaps the system should not care about. We will set this theoretical framework aside for the time being.  We will first analyze a paradigmatic legal case that features gaps in the evidence. This case will allow us to become familiar with the legal framework for dealing with missing evidence. 
We will then see how the theoretical framework can illuminate---and guide---how the law handles gaps in the evidence.



# Legal Framework

We start by recounting the facts of a paradigmatic case of missing evidence. 
This discussion will then serve to outline
the legal framework for addressing questions of missing evidence.

## Missing Evidence in a Legal Case 

In a nutshell, the facts are as follows.^[Details of the case are as follows: Decker v. Target Corp, Case No. 1:16-cv-00171-JNP-BCW, Filed 10/10/2018] The accident occurred at Target, a chain  of department stores in the United States. The customer slips, falls and gets injured in a Target store because of a flatbed, possibly left unattended. The customer suffers serious injury and is transposed to a hospital. The customer sues Target and seeks to recover damages. However, video surveillance footage is only preserved in part. The rest is destroyed. It is impossible to reconstruct exactly what happened before the incident. Before trial, the plaintiff---the customer bringing forth the accusation---seeks an adverse inference jury instruction against Target for failing to preserve the surveillance video. The Court agrees and instructs the jury they can presume that the cart had been left unattended.^[The outcome of the jury trial, however, favors Target, not the customer: "Case Number: 1:16-cv-00171-JNP. Outcome: JUDGMENT - This action came before the court for a trial by jury. The issues have been tried and the jury has rendered its verdict. IT IS ORDERED AND ADJUDGED that judgment is entered in favor of defendant Target Corporation and against plaintiffs Caryl Jean and Dennis Decker. Case Closed. Magistrate Judge Brooke C. Wells no longer assigned to case. Signed by Judge Jill N. Parrish on 10/22/2018. (jds) (Entered: 10/22/2018)" https://www.morelaw.com/verdicts/case.asp?n=1:16-cv-00171-JNP&s=UT&d=121221]


It pays to reconstruct the facts more in detail, using 
excerpts from a court ruling on the motion 
for adverse jury instructions  submitted by the plaintiff.^[Motion available at: https://cloudnine.com/wp-content/uploads/2018/10/Decker-v.-Target-Corp._2018-10-28-20_38_58-0400.pdf] The case is quite complex. 
The incident occurred on December 26, 2015, at the Target 
store located in Riverdale, Utah:
<!--This Motion arises from a trip and fall incident that occurred on December 26, 2015, at the Target store located in Riverdale, Utah. --->

\begin{quote}
Caryl Jean Decker was shopping when she tripped on a flatbed stocking cart and
fell onto the floor, suffering serious injury. Mrs. Decker, bleeding from the head, received medical attention at the scene of the incident. She was transported from Target by ambulance.
\end{quote}

\noindent
The incident was recorded in its entirety 
by Target's surveillance camera. However, only a short portion of the video was preserved, just a few seconds depicting the fall. The portions of the video before and after the incident was erased. 

The first question is whether Target should have preserved the video recording in its entirety. For one thing, plaintiff made a prompt and explicit request to preserve all relevant portions of the recording one month after the incident.^["Exactly one month after the incident, on January 26, 2016, the Deckers delivered a letter to Target, through counsel, requesting that Target preserve “all pertinent records and electronic records pertaining to [the] incident or that could relate to [the] incident,” as well as “a copy of any video surveillance that shows [the] accident or the area of the accident at any time before, during, or after the event.” Motion for Findings of Spoliation and for Sanctions (“Motion”) Exhibit 6."]
On the other hand, Target's policy was to preserve 
recordings for no more 
than twenty-five days.^["The unsaved portions of the footage were later automatically overwritten by Target’s system, which only maintains video surveillance footage for approximately fifteen to twenty-five days."]
Target could argue---as it did---that it followed its policy. But the question, as the Court noted, was whether Target had a duty to preserve a more extended version of the recording. The Court reasoned that Target knew---or should have known---that litigation was imminent:

\begin{quote}
 In this case, it is apparent that Target was on notice that litigation was
imminent when Mrs. Decker tripped, fell, and left the Target store in an ambulance on December 26, 2015. Target argues it was not on notice until the Deckers’ demand letter arrived on January 26, 2016; however, that argument is disingenuous. Mrs. Decker fell and an ambulance was called. This was a “guest incident” of the sort that Target’s internal policies note create the “potential for a general liability claim to be brought
against Target.” 
\end{quote}

\noindent 
So, even though Target's general policy is to delete videos after twenty-five days, this policy is overwritten in special circumstances, for example, when litigation is imminent. In deleting the relevant portions of the video, Target's violated its own policy pertaining to imminent litigation. All in all, then, Target should have preserved the video it deleted.

Another question is whether the missing video recording 
negatively prejudiced the plaintiff.  Here, too, the answer is affirmative. Because 
of the missing video, the plaintiff could not make their case, since there was hardly any other source of information about what happened around the cart that day:

<!---Interestingly, plaintiff does not rely on rule 37(e) but some other spoliation legal doctrine.  Not sure why.

\begin{quote}
The Deckers, having failed to seek sanctions under Fed. R. Civ. P. 37, seek sanctions under a spoliation of
evidence theory. See Turner v. Pub. Serv. Co. of Colo. , 563 F.3d 1136, 1149 (10th Cir. 2009) (quoting Mathis v. John Morden Buick, Inc., 136 F.3d 1153, 1156 (7th Cir. 1998) .... “Spoliation sanctions are proper when ‘(1) a party has a duty to preserve evidence because it knew, or should have known, that litigation was imminent, and (2) the adverse party was prejudiced by the destruction of the evidence.’ ” Turner, 563 F.3d at 1149 (quoting Burlington Northern \& Santa Fe Ry. Co. v. Grant , 505 F.3d
1013, 1032 (10th Cir. 2007)).
\end{quote}

--->

\begin{quote}
Due to this deletion, the Deckers do not know who placed the flatbed stocking cart at the location of the incident, how long it was there, or why it was there. The Deckers are not prejudiced by the lack of evidence of who placed the flatbed cart because Target does not contest that it was placed on the floor by one of Target’s own employees. However, the Deckers are prejudiced by the lack of footage that would have documented  whether or not the cart was being “worked” or “attended” by a Target employee.
\end{quote}


<!---
\begin{quote}
To support a finding of spoliation of evidence, the Deckers must establish that Target has deleted or failed to preserve relevant evidence and that they have been prejudiced thereby. The court concludes that the Deckers have met this burden with respect to the deleted video surveillance footage.
\end{quote}
--->

\noindent
So, the Court established that, first, there was a duty to preserve the video footage, and second, the missing video created prejudice against the plaintiff.^[This is the legal doctrine followed in the case: "Spoliation sanctions are proper when ‘(1) a party has a duty to preserve evidence because it knew, or should have known, that litigation was imminent, and (2) the adverse party was prejudiced by the destruction of the evidence.’" Turner, 563 F.3d at 1149 (quoting Burlington Northern \& Santa Fe Ry. Co. v. Grant , 505 F.3d 1013, 1032 (10th Cir. 2007)).] These two points, however, are not enough to warrant an adverse jury instruction against Target The adverse instruction is justified provided there was bad faith on the part of Target.^["To be entitled to an adverse inference instruction,
the Deckers must establish that Target acted in bad faith in failing to preserve the evidence at issue."]

Did Target act in bad faith in deleting the relevant portions of the videos? The issue here is muddled, but the basic rationale the Court followed is this. First, Target went against its own policy and deleted relevant video recordings that its own policy would mandate to preserve. In addition, Target tried to argue that the flatbed was attended by an employee (which is an issue that cannot be litigated since the relevant recording was destroyed).
More specifically, this is what the Court wrote:
\begin{quote}
In the footage that remains, there is no evidence of a Target employee working the flatbed cart, nor does the flatbed cart appear to move in the eleven-minute gap between the two clips. A reasonable juror could infer that the cart was unattended. However, in defending against the Deckers’ claims, Target intends to offer evidence that one or more Target employees were working or attending the cart ... the Deckers ... have no way to disprove that evidence."
\end{quote}

\noindent
Both considerations---one: Target's violation of its policy; two: Target's attempt to take advantage of the missing evidence that it itself caused---suggest bad faith on the part of Target as a corporation.^[There was no bad faith on the part of the individual who deleted the video. The employees who deleted the video claim they were not aware of Target's policy pertaining to imminent litigation. More specifically, this is the reasoning of the Court more in detail: "First, Target failed to instruct its employees regarding Target policy of what footage to preserve. Second, Target employees failed to preserve all relevant footage. And third, Target’s counsel now seeks to take advantage of the evidence that Target failed to preserve by arguing that the flatbed cart was attended or worked by Target employees during the gap in the video. It is this attempt to take advantage of a situation that Target caused that leads the court to conclude Target acted in bad faith."] So the Court granted the adverse inference jury instruction, specifically:
\begin{quote}
The court will therefore instruct the jury to make the adverse inference that the flatbed cart was unattended for the twenty minutes prior to the accident.
\end{quote}

<!---
It instructed the jury they could presume presumption the missing video recording did show that the flatbed was actually unattended:
--->


TO ADD, MENTION OTHER SIMILAR CASES: E.G. SALEM TRIALS

NEXT, TRANSITION TO LEGAL FRAMEWORK

NOTE THAT MISSING EVIDENCE HERE IS CLEARLY DEFINED, IT IS NOT GENERIC, THERE IS A STORY WHICH CLEARLY SHOWS EVIDENCE IS MISSING. TERMINOLOGY: MANIFEST GAPS (MISSING VIDEO) VERSUS OPEN-ENDED GAPS (MISSING STATS ABOUT RELIABILITY). EXPRESSION "OPEN-ENDED GAPS" MIGHT SOUND STRANGE. 



## Relevance, prejudice, and remedies
 
The legal framework for dealing 
with missing evidence is informed
by a number of questions. They pertain to 
the relevance of the missing evidence, its prejudicial effects, and the remedies 
that can be applied. Considerations about why the evidence is missing are also important.

\begin{itemize}
\item[] Relevance - Is the missing evidence relevant?
\item[] Prejudice - Could the missing evidence make a difference to the decision?
\item[] Remedy - What remedies should be granted to the litigant disadvantaged 
by the missing evidence?
\item[] Explanation - Why is the evidence missing? Was it an accident or  misconduct?
\end{itemize}


The first two questions form a yes/no flowchart. First, if the missing evidence is not relevant, the question of prejudice does not arise. Missing evidence is evidence whose content is generally unknown. If its content were known, the evidence would not be missing (though even this point can be contested; more soon). So, in order to be relevant, missing evidence should strengthen or weaken the case of one of the litigants. Short of that, the evidence could be disregarded.  For example, suppose the defendant is charged with illegal possession of firearm. The police legally searched the defendant's vehicle and found a firearm in a backpack. The defendant had no permit. The police does not retain all the items in the backpack. The defense complains during trial that the evidence is incomplete: information about the contents of the backpack is missing. Here it seems that the missing evidence is irrelevant. The evidence available shows conclusively that the defendant was carrying a firearm without a permit. The exact content of the backpack does not make any difference.^[Howard - No. 18-CF-157 District of Columbia Court of Appeals
Link to case: https://www.casemine.com/judgement/us/5fbb6f1d4653d07a51f93921] Of course, some might be wonder, what if the backpack contained information that showed that someone else placed the firearm in the defendant's backpack with the intent to getting the defendant's arrested? The question of relevance---as well as the other questions---requires a standard by which they should be answered. The standard here could be that, unless the missing evidence is \textit{clearly} relevant, the evidence counts as irrelevant. This is just an illustration. The point here is only that a standard must be set by which the answer to the question of relevance can be adjudicated. 

Suppose the missing evidence is clearly relevant. The missing video recording in the trip and fall case at the beginning is clearly relevant. Whatever the content of the recording, it could strengthen the plaintiff's case or weaken it. But, even if the evidence is relevant, it can make no difference to the decision. When this is the case, the missing evidence would raise no question of prejudice. The question of prejudice arises whenever the missing evidence could have turned a liability decision into a non-liability decision or the other way around. Consider both cases. In the trip and fall case, the available evidence is in equipoise. Thus, based solely on the evidence available, the case should be resolved in favor of the defendant, a finding of no-liability. However, suppose the video recording showed that the customer tripped and fell because of negligence by the shop owner: a bottled spilled and made the floor wet; the floor was left unattended for a while with no signs. Then, given the recording, the defendant would have---or at least, could have reasonably----been found liable. Prejudice can also work in the other direction. Suppose a witnessed testified against the shop owner, but a second witness was not called to testify. Based on the available evidence, the balance of the evidence tips in favor of the plaintiff. But, the second witness could have given a different recounting of the facts, more favorable to the shop owner. Their story could have brought the balance of the evidence in equipoise, thus recommending a finding of non-liability. Whether the evidence is prejudicial might itself disputed. Like with the question of relevance, a standard is needed by which to decide the question of prejudice. The standard could be along these lines: when interpreted in the light most favorable to the side that could be prejudiced, would the missing evidence change the decision according to the governing decision rule?

Once it is clear that the missing evidence is relevant and its absence prejudicial, the question of which remedy should be applied, if any, arises. This question offers great latitude.  An extreme remedy would be that this: if there is missing relevant and prejudicial evidence that goes to the detriment of the accused party, the case should be decided and thus the accusation is dismissed. This remedy seems excessive: it will likely create a perverse incentive for defendants to destroy evidence in their favor. The absence of any relevant evidence that could be prejudicial for them---in this case, evidence in favor of the defendant---would be enough to dismiss the accusation. So, instead of presenting exculpatory evidence that would examined via the process of cross-examination, defendant would simply choose to destroy that evidence and that claim they were prejudiced and thus they should win the case. This arrangement makes little sense. Alternatively, the remedy could apply only provided the party bringing the accusation was responsible for destroying the evidence favoring the defendant. 

Remedies could also apply at the level of how the evidence is assessed, not at the level of decisions. So, for example, the remedy could be this: the part responsible for the missing evidence and that attempted to benefit from the missing evidence should see their case weakened by some amount of evidential force (proportionate to the extent to which the part sought to benefit by causing the gap). There may be many other possible formulations. 
For example, in the Target's case the remedy was an adverse jury instruction to presume a fact obtained, where the presumed weakened the case of the party that, in bad faith, contributed to the destruction of the evidence.

Another approach would be to initiate a separate litigation for missing evidence. This might be more appropriate in criminal then civil cases. To penalize criminal defendants with an adverse jury instructions because they destroyed evidence may clash with other well-established rights defendants have, such as the right to be presumed innocent until proven guilty. At the same, destruction of incriminating evidence must be adversely sanctioned. To this end, destruction or tainting of evidence relevant for criminal litigation can count as a wrongdoing in itself which can be litigated in a separate trial. This should provide the right incentive for people not to destroy evidence. 
 

# Epistemology or policy?

It is clear that remedies about missing evidence---whatever their exact articulation--cannot be decided without answering the question of why the evidence in question had gone missing. The question of bad faith intent seems crucial in formulating the appropriate remedy. After all, it would seem odd---or even downright immoral---to penalize a party that would otherwise benefit from the fact that some evidence is missing 
even though the party had no responsibility in bringing about the fact of missing evidence.
Instead, it is less objectionable to formulate a remedy for missing evidence along these lines: if available evidence cannot settle a factual dispute between litigants and a litigant destructed relevant evidence with bad faith intent of benefiting from the destruction, the dispute should be resolved against the litigant; if, however, the lack of evidence tips the scale in favor of a litigant who however did not maliciously act to destroy the evidence, the issue must be resolved in favor of that litigant in accordance to the balance of the available evidence. Why would justify this rule? Presumably, this rule would create forward-looking incentives for litigants not to destroy evidence with the intent of benefiting from the destruction.  

But remedies to gaps in the evidence may have a more straightforward epistemic goal, internal to the logic of evidence evaluation. Why should the litigant who destroyed the evidence with bad faith intent be penalized? The following inference is plausible: the missing evidence that was destroyed would be in favor or against the litigant. It is unlikely that a litigant would destroy evidence in their favor, and thus the evidence must have been unfavorable to them. If the evidence was unfavorable to them and had the evidence not been destroyed, the balance of the evidence would have tipped against the defendant. Hence, the dispute must be resolved against the litigant who destroyed the evidence. This analysis does not justify the remedy to gaps based on any specific policy objectives. In fact, this analysis simply aims to assess the evidence conscientiously and draws inference about missing evidence---its treats missing evidence as another fact that can be used as information to draw inference about the disputed facts. 

So we have two approaches here to conceptualize gaps in the evidence. One approach sees these remedies as an application to a conscientiousness assessment of the evidence: that some evidence is missing becomes itself information (evidence) that helps to draw inference together with other evidence. This a purely epistemic approach, internal to the logic of evidence evaluation. The other approach views gaps in the evidence as a a result of objectionable out-of-court behavior that must be sanctioned. Call this the policy approach. The two approaches are not exclusive, but one question is whether the epistemic approach can cover all cases or the policy approach is needed. It may be that we cannot draw any inference about the missing evidence one way or another---say the video is missing because of an accidental blackout or a glib in the system. Both sides are disadvantaged by the missing evidence: the shop-owner cannot prove the were not negligent; the customer cannot prove this case against the shop.  So what is the remedy here? It seems here a matter of policy what to do. But since there is no obviously culpable behavior responsible for the missing evidence, maybe the answer is just: do nothing. Here is another case. The shop-owner only stored the videos for a week and the lawsuit came right after that week.  So against, there seems to be no culpability; no adverse inference against the shop-owner. But perhaps the policy remedy could be to rule in favor of the custom to create an incentive for shop-owner to preserve video recording for longer period of time or simply create a precedents.

The general question is, what are these policy-driven remedies intended to achieve? In the case of the epistemic remedies the goal is clear---evaluate the evidence carefully---but when policy remedies are introduced, what is their goal? The next section takes a set back back and looks at the problem of evidential gaps from a more general perspective. We hope to return to these questions afterwards.






# Conjectural gaps

Legal framework only considers cases when we know evidence is missing. We know something happened and we know evidence went missing. There is a clear story about the evidence missing. But what if evidence is missing in a more generic, conjectural sense?

There seems to be two cases here:

(1) Additional of evidence missing fits a clear story and thus we can tell that, if that evidence is added, the decision would be overall of a better quality, so FP and FN rates would both go down in those kind of cases. These are cases considered in the legal framework.

(2) Additional evidence does not fit a clear story so we only know it could be relevant in general, but we cannot whether, once added to the body of evidence, it would make it of better or worse quality. This seems more like the case below we add evidence that is available in 20\% and we make the error rates worse in those 20\% of cases. So the limitation of the legal framework to those cases seems justified. 

(3) What to say about missing evidence about the reliability of eyewitness or some testing procedure? Is it good or bad to have that evidence and should there be a missing evidence instruction in those cases? Is it more like (1) or (2) above? Think about Bayesian network about lighting conditions in the awareness growth paper.


# Tentative general theory

Here is a tentative general theory, also based on what is said in 
the section below: wherever the missing evidence is the result 
of an action that can be ascribed to a biased, 
patterned systematic removal of the evidence, then that action must be penalized. If the missing the evidence is fortuitous or random, then no action is needed. 















 


 


 

# Paradigmatic cases

This section examines a few paradigmatic cases 
of missing evidence. This examination also details the 
complexities associated with missing evidence and the legal 
framework in place to deal with missing evidence. 
We will draw from civil and criminal trials.



## Example: Salem Trials

Summarize facts of the case.
Identify missing evidence.
Question of whether there was missing evidence (yes), a justification for the missing evidence (yes/no), prejudice about missing missing (yes/no).
The peculiarity about this case is that the content of the missing evidence is relatively clear -- what the witness presumably saw is known --  though the evidence cannot be tested. 




## Hamer's argument

**Hamer's first claim:** New evidence can turn out to be positive (say incriminating) or negative (exculpatory). Since one cannot know that in advance, the expected probability based on this added evidence (which can be positive or negative) is just the probability based on the current evidence. He proves this claim analytically in the appendix to his paper.


\begin{quote}
More generally, if the evidence is missing it cannot be known which way it points.
It appears equally possible that the missing evidence would confirm the current factual conclusion as
contradict it. The competing possibilities cancel each other out. There is no warrant for the assumption
that the missing evidence will point one way rather than the other. (p. 139)
\end{quote}

**Comment:** This claim seems right, but there is one puzzling thing. In our paper on unanticipated possibilities and Bayesian networks, we show that---given a certain causal structure of the Bayesian network (=collider with two upstream nodes incoming into downstream evidence hypothesis, the added node is upstream)---merely positing that there could be new information (say we could learn the witness was unreliable or  reliable) would change the initial probability assessment (without learning about the value of the evidence). This is not true in other cases in which the Bayesian network has a serial structure and the added node is downstream and not upstream. So, while Hamer is right in the most abstract sense, there might be causal structural features of a case (as captured by a Bayesian network) that do warrant changing one's probability assessment in virtue of learning that that could be other evidence (even though you do not know what that evidence actually is).


# From Manifest to Conjectural Gaps











# Referennces
