---
title: "Coherence"
author: "Marcello/Rafal"
output:
  pdf_document:
    number_sections: true
    df_print: kable 
    keep_tex: true
    includes:
      in_header:
        - style.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 11pt
documentclass: scrartcl
urlcolor: blue
bibliography: [../references/referencesMRbook.bib]
csl: [../references/apa-6th-edition.csl]
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Questions

- How do we define coherence of a story (narrative, etc.)?

- Coherence of what? Is just the coherence of a set of statements (making up a story, narrative, etc.)? Or does coherence also involve the statements describing the supporting evidence?

- If coherence also takes into account the supporting evidence, should evidence be given a more entrenched status (a weak form of foundationalism)? Or do statements about facts (elements of a story) and statements about evidence play the same role in an account of coherence?

- What is the relationship between coherence and corroboration (congruence of different, independent witness reports)? is corroboration a specific case of coherence?

- What is the connection between accuracy, coherence and probability? Is coherence a good guide to truth?

- Why is coherence important? How can it be---should it be---used as a decision criterion in trial proceedings?

- Is coherence a single notion or multilevel notion, a combination of various theoretical virtues such as specificity, explanatory power, plausibility, consistency with background beliefs, etc.?



# Philosophical proposals (from SEP entry on Coherence)


## Ewing (1934): consistency plus mutual logical support

"According to Ewing, a coherent set is characterized partly by consistency and partly by the property that every belief in the set follows logically from the others taken together."


## Lewis: mutual probabilistic support

"As Lewis defines the term, a set of 'supposed facts asserted' is coherent (congruent) just in case every element in the set is supported by all the other elements taken together, whereby 'support' is understood not in logical terms but in a probabilistic sense"

## Bovens and Olsson 2000: mutual probabilistic support (of subsets)

"Against Lewis’s proposal one could hold that it seems arbitrary to focus merely on the support single elements of a set receive from the rest of the set (cf. Bovens and Olsson 2000). Why not consider the support any subset, not just singletons, receives from the rest?"

## Laurence BonJour (1985): multilevel coherence

Coherence of a system of beliefs depends on:

1. logical consistency

2. degree of probabilistic consistency

3. presence of inferential connections between its component beliefs and the number and strength of such connections (or proportional density of such  connections)^["BonJour’s third criterion, taken at face value, entails therefore that a bigger system will generally have a higher degree of coherence due to its sheer size. But this is at least not obviously correct. A possible modified coherence criterion could state that what is correlated with higher coherence is not the number of inferential connections but rather the inferential density of the system, where the latter is obtained by dividing the number of inferential connections by the number of beliefs in the system."]

4. coherence is diminished if system of belief is divided into subsystems of beliefs which are relatively unconnected to each other by inferential connections.

5. coherence is diminished by presence of unexplained anomalies in the believed content of the system.


##  Rescher 1973: maximal consistency plus plausibility


"the purpose of Rescher’s investigation is ... to find a truth criterion ... a systematic procedure for selecting from a set of conflicting and even contradictory truth-candidates those elements which it is rational to accept as bona fide truths."

"His solution amounts to first identifying the maximal consistent subsets of the original set, i.e., the subsets that are consistent but would become inconsistent if extended by further elements of the original set, and then choosing the most 'plausible' among these subsets. Plausibility is characterized in way that reveals no obvious relation to the traditional concept of coherence."

## Thagard: explanatory coherence


## Lewis Bonjour debate abut congruent reports (corroboration?)

Take two witnesses who say the same thing about a certain matter (congruence of reports). So there is coherence (congruence, corroboration?) between the content of their assertions. 

- Lewis position: "if the beliefs in a set have no initial credibility, then no justification will ensue from observing the coherence of that set. Thus, Lewis is advocating weak foundationalism rather than a pure coherence theory." 

- Bonjour position:  coherence triggers a confidence boost even without an antecedent credibility of the individual beliefs, contrast Lewis

Lewis seems right because the following are inconsistent in probability theory:

(a) conditional independence of items of evidence $E_1$ and $E_2$ relative to a statement $A$ (the statement about which the reports are congruent), 

(b) non foundationalism (i.e. individual reports $E_1$ and $E_2$ do not raise, taken separately, the probability of $A$) and

(c) coherence justification (i.e. reports taken together do raise the probability of $A$).

Unlike Lewis, Bonjour believes that (c) can exist without (b).

## Probabilistic measure of coherence

SEP has a quick discussion of these measures, includign a mesure by Fitelson. 
This is better summarized in Urbaniak and Kowalewska's paper on coherence. Check!

## Coherence and truth conduciveness

There is an "Analysis debate" about whether coherence is truth conducive.

- One might say the more statements, the less probable, but the more coherent. Thus, coherence is not truth conducive (does not lead to higher probability) simply because   $\pr{A\wedge B}>\pr{A\wedge B\wedge C}$ even though $A\wedge B$ may be less coherent than $A\wedge B\wedge C$.

- But what if we consider the supporting evidence? Is it the case that also $\pr{A\wedge B \vert E_a, E_b}>\pr{A\wedge B\wedge C \vert E_a, E_b, E_c}$. 

- Incidentally, this seems to connect with the conjunction problem as well as the discussion between accuracy and specificity.

- Also, is it correct to define truth-conduciveness in terms of probability?

## Impossibility results: Bovens and Hartmann (2003) and others

This draws from the Lewis/Bonjour debate, probabilistic measures of coherence and truth conduciveness debate. 

- "The question of interest, then, is whether more coherence implies a higher probability (given independence and individual credibility) everything else being equal. We are now finally in a position to state the impossibility theorems. What they show is that no measure of coherence is truth conducive even in a weak ceteris paribus sense, under the favorable conditions of (conditional) independence and individual credibility."

-  Key idea of the proof: "They show that there are sets S and S', each containing three propositions, such that which set is more likely to be true will depend on the level at which the individual credibility (reliability) is held fixed. Thus for lower degrees of reliability, one set, say S, will be more probable than the other set, S'; for higher degrees of reliability, the situation will be reversed. One can now find a counterexample to the truth conduciveness of any measure C through a strategic choice of the level at which the reliability is held fixed."

- This gives rise to a paradox: "These impossibility results give rise to a thought-provoking paradox. It can hardly be doubted that we trust and rely on coherence reasoning when judging the believability of information, in everyday life and in science ... But how can this be when in fact coherence is not truth conducive?"

Some thoughts and questions:

- Don't Urbaniak and Kowalewska show that their measure of coherence is truth conducive? How does their notion of structured coherence fit into the debate about these impossibility results?

- The other notes on specificity and accuracy claims that a more specific story is better for accuracy even though a more specific narrative is less probable. So the issue here might that high probability is not the right guide to accuracy or truth, however strange that may sound. So the denate is based on that false assumption. No one seems to question that assumption. To be explored more. 














