---
title: "Higher-order Legal Probabilism"
author: 
  - Rafal Urbaniak^[University of Gdansk and Basis.ai]
  - Marcello Di Bello^[Arizona State University - mdibello@asu.edu]
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    number_sections: false
    df_print: kable 
    keep_tex: true
    toc: no
    includes:
      in_header:
        - Rafal_latex7.sty
classoption: dvipsnames,enabledeprecatedfontcommands
fontsize: 10pt
documentclass: scrartcl
urlcolor: blue
bibliography: [../../references/referencesMRbook.bib]
csl: [../../references/apa-6th-edition.csl]
indent: true
---

\paragraph{Type of contribution:} Oral presentation type 1, 45 minutes 

\paragraph{Keyworks:} likelihood ratio; strength of evidence; Bayesian network; higher-order probability 


\paragraph{The problem}
It is standard to assess the strength of evidence using likelihood ratios, at least for quantitative evidence such as genetic matches. For example, the likelihood ratio of interest can be P(match evidence / source hypothesis)/P(match evidence / alternative to source hypothesis). Simplifying a bit, this likelihood ratio can be approximated by $1/f$ where $f$ is the expected frequency (or proportion) of the matching genetic profile in a reference population.  The $1/f$ ratio captures some of the uncertainty associated with the match in relation to the source hypothesis, but also leaves out crucial information.  After all, the expected frequency may have been arrived at in different ways, say, via a larger or smaller sample.  Should an additional measure of uncertainty accompany the likelihood ratio itself? 

\paragraph{The state of play}
A debate is ongoing in the forensic science literature on whether likelihood ratios should also be accompanied by a measure of precision, confidence or an interval estimation. (See, e.g., the 2016 special issue of *Science and Justice*, "Special issue on measuring and reporting the precision of forensic likelihood ratios", edited by G.S. Morrison.) Some scholars note that the likelihood ratio is not a parameter to be estimated, and thus all the uncertainty -- including sampling uncertainty -- should be encapsulated into a single number. Others believe that sampling uncertainty should be modeled separately, for example, via an interval estimation. Interestingly, this debate among forensic scientists parallels a philosophical debate on how probabilities can model a rational agent’s evidence-based beliefs. One approach, known in the philosophical literature as precise probabilism, posits that an agent’s credal state is modeled by a single, precise probability measure. Another approach, known as imprecise probabilism, replaces precise probabilities by sets of probability measures. The philosophical literature contains arguments for and against each of these views.

\paragraph{Contribution}
We favor a third approach, what we call higher-order probabilism, which relies on distributions over probabilities. We show that there are good theoretical reasons to abandon both precise and imprecise probabilism and endorse higher-order probabilism. This claim has applications to the debate in forensic science. We argue that a second-order uncertainty should be taken into account when we assess, in probabilistic terms, the strength of match evidence. Instead of single-number likelihood ratios or intervals, we propose that higher-order likelihood ratios be used. This approach is consistent with Bayesianism in epistemology and does not require treating likelihood ratios as parameters to be estimated.  In addition, we show that higher-order probabilism can be scaled to model complex bodies of evidence. Standard, single-number likelihood ratios associated with different pieces can be combined together to model complex structures of evidence by means of Bayesian networks. The same is possible for higher-order likelihood ratios. To this end, we sketch a formalism for constructing what we call higher-order Bayesian networks. We illustrate this higher-order approach by revisiting familiar cases in the literature such as Sally Clark and Charles Shonubi.
 
